const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.video,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Behaviors.LOS,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.Anchor,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{logo: 0},
	{Mouse: 0},
	{Touch: 0},
	{TimelineController: 0},
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_installgamebutton: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_update_button: 0},
	{adl_white_back: 0},
	{Menugirl: 0},
	{Menuray: 0},
	{Menutext: 0},
	{Menubg: 0},
	{Physics: 0},
	{basket: 0},
	{LineOfSight: 0},
	{bomb: 0},
	{Gamebg: 0},
	{Sine: 0},
	{GameFlower: 0},
	{immoveableBox: 0},
	{jumpPlus: 0},
	{Jump: 0},
	{movableBox: 0},
	{Star: 0},
	{Stick: 0},
	{Stick2: 0},
	{Stone: 0},
	{Strawberry: 0},
	{Tree: 0},
	{Pin: 0},
	{end: 0},
	{wall: 0},
	{Sprite: 0},
	{Fadein: 0},
	{Fadeout: 0},
	{StoryBg: 0},
	{Storygirl: 0},
	{StoryStrawberry: 0},
	{StoryTree: 0},
	{Locked: 0},
	{Level: 0},
	{isFirst: 0},
	{Btn: 0},
	{LevelText: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{SpriteFont: 0},
	{istext: 0},
	{SpriteFont2: 0},
	{Flash: 0},
	{starttext: 0},
	{Text: 0},
	{NumberFonts: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{homeBtn: 0},
	{PlayBtn: 0},
	{Anchor: 0},
	{ReplayBtn: 0},
	{Back_Variable: 0},
	{back_btnasset: 0},
	{htp: 0},
	{menu_btnasset: 0},
	{Next_Variable: 0},
	{next_btnasset: 0},
	{tutorial: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{GameMonetizeSDK: 0},
	{levelCount: 0},
	{PassedLvl: 0},
	{CurrentLevel: 0},
	{ScreenSize: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	logo: class extends self.IWorldInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	Menugirl: class extends self.ISpriteInstance {},
	Menuray: class extends self.ISpriteInstance {},
	Menutext: class extends self.ISpriteInstance {},
	Menubg: class extends self.ITiledBackgroundInstance {},
	basket: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	Gamebg: class extends self.ISpriteInstance {},
	GameFlower: class extends self.ISpriteInstance {},
	immoveableBox: class extends self.ISpriteInstance {},
	Jump: class extends self.ISpriteInstance {},
	movableBox: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Stick: class extends self.ISpriteInstance {},
	Stick2: class extends self.ISpriteInstance {},
	Stone: class extends self.ISpriteInstance {},
	Strawberry: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Fadein: class extends self.ISpriteInstance {},
	Fadeout: class extends self.ISpriteInstance {},
	StoryBg: class extends self.ISpriteInstance {},
	Storygirl: class extends self.ISpriteInstance {},
	StoryStrawberry: class extends self.ISpriteInstance {},
	StoryTree: class extends self.ISpriteInstance {},
	Btn: class extends self.ISpriteInstance {},
	LevelText: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	starttext: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	NumberFonts: class extends self.ISpriteFontInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	PlayBtn: class extends self.ISpriteInstance {},
	ReplayBtn: class extends self.ISpriteInstance {},
	back_btnasset: class extends self.ISpriteInstance {},
	htp: class extends self.ISpriteInstance {},
	menu_btnasset: class extends self.ISpriteInstance {},
	next_btnasset: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}