const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Arr.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Particles.Cnds.CompareX,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Arr.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Selected: 0},
	{vFrame: 0},
	{Tween: 0},
	{blocks: 0},
	{bg_blocks: 0},
	{StartX: 0},
	{StartY: 0},
	{Frame: 0},
	{Direction: 0},
	{bg_game: 0},
	{Load: 0},
	{aBlockGrid: 0},
	{aBlockGridEx: 0},
	{AJAX: 0},
	{Touch: 0},
	{p_blocks: 0},
	{blocks_shadow: 0},
	{btn_lvl: 0},
	{btn_reset: 0},
	{btn_sound: 0},
	{btn_music: 0},
	{Interpolação: 0},
	{txt_currentlvl: 0},
	{movegrid: 0},
	{moveexgrid: 0},
	{Fade: 0},
	{efx_touch: 0},
	{efx_touch_P: 0},
	{fade: 0},
	{bg_black: 0},
	{txt_lvlwin: 0},
	{txt_win: 0},
	{btn_next: 0},
	{line: 0},
	{Mouse: 0},
	{Sine: 0},
	{SineSize: 0},
	{SineSize2: 0},
	{logo: 0},
	{btn_play: 0},
	{Number: 0},
	{btn_levels: 0},
	{btn_home: 0},
	{txt_levelnu: 0},
	{txt_leveltitle: 0},
	{aLevel: 0},
	{QuantityStar: 0},
	{icon_starsG: 0},
	{txt_touchq: 0},
	{level: 0},
	{icon_starsL: 0},
	{aStar: 0},
	{LocalStorege: 0},
	{Esmaecer: 0},
	{P_Confetti: 0},
	{Rotate: 0},
	{Sine2: 0},
	{Confetti: 0},
	{Keyboard: 0},
	{cir_tutorial: 0},
	{icon_tutorial: 0},
	{txt_build: 0},
	{Audio: 0},
	{btn_clean: 0},
	{btn_m: 0},
	{Browser: 0},
	{btn_more: 0},
	{GameMonetizeSDK: 0},
	{tween: 0},
	{f_btns: 0},
	{vChooseDi: 0},
	{vChooseFre: 0},
	{vChooseAniBlock: 0},
	{Touched: 0},
	{PositionX_01: 0},
	{PositionY_01: 0},
	{PositionX_02: 0},
	{PositionY_02: 0},
	{vStar: 0},
	{vCurrentLevel: 0},
	{QuantityTouch: 0},
	{OpacityWin: 0},
	{OpacityOff: 0},
	{Sound: 0},
	{Music: 0}
];

self.InstanceType = {
	blocks: class extends self.ISpriteInstance {},
	bg_blocks: class extends self.ISpriteInstance {},
	bg_game: class extends self.ISpriteInstance {},
	aBlockGrid: class extends self.IArrayInstance {},
	aBlockGridEx: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	p_blocks: class extends self.IParticlesInstance {},
	blocks_shadow: class extends self.ISpriteInstance {},
	btn_lvl: class extends self.ISpriteInstance {},
	btn_reset: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	txt_currentlvl: class extends self.ITextInstance {},
	movegrid: class extends self.ISpriteInstance {},
	moveexgrid: class extends self.ISpriteInstance {},
	efx_touch: class extends self.ISpriteInstance {},
	efx_touch_P: class extends self.IParticlesInstance {},
	fade: class extends self.ISpriteInstance {},
	bg_black: class extends self.ISpriteInstance {},
	txt_lvlwin: class extends self.ITextInstance {},
	txt_win: class extends self.ITextInstance {},
	btn_next: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	logo: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_levels: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	txt_levelnu: class extends self.ITextInstance {},
	txt_leveltitle: class extends self.ITextInstance {},
	aLevel: class extends self.IArrayInstance {},
	icon_starsG: class extends self.ISpriteInstance {},
	txt_touchq: class extends self.ITextInstance {},
	icon_starsL: class extends self.ISpriteInstance {},
	aStar: class extends self.IArrayInstance {},
	LocalStorege: class extends self.IInstance {},
	P_Confetti: class extends self.IParticlesInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	cir_tutorial: class extends self.ISpriteInstance {},
	icon_tutorial: class extends self.ISpriteInstance {},
	txt_build: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	btn_clean: class extends self.ISpriteInstance {},
	btn_m: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	btn_more: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	f_btns: class extends self.ISpriteInstance {}
}