const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Interpolação: 0},
	{Âncora: 0},
	{Btn_Home: 0},
	{Btn_Info: 0},
	{Btn_Levels: 0},
	{Btn_lvl: 0},
	{Side: 0},
	{Positon: 0},
	{Btn_Next_Left: 0},
	{Btn_Next_lvl: 0},
	{Btn_Next_Right: 0},
	{Btn_Restart: 0},
	{Number: 0},
	{Btn_Select_LvL: 0},
	{Btn_Sound: 0},
	{BtnPlay: 0},
	{Tween: 0},
	{btn_m: 0},
	{txt_lvl_InGame: 0},
	{txt_lvl_Number: 0},
	{txt_lvl_Select: 0},
	{Esmaecer: 0},
	{txt_PaintColor: 0},
	{txt_timerBarSecunds: 0},
	{txt_AndGame: 0},
	{GameOver: 0},
	{Icon_bgTimer: 0},
	{Icon_bgTimer2: 0},
	{Icon_Timer: 0},
	{Icon_Tutorial: 0},
	{Info: 0},
	{Senóide: 0},
	{Logo: 0},
	{Win: 0},
	{Range: 0},
	{SmallBackground: 0},
	{Blocks: 0},
	{Directions: 0},
	{Brush: 0},
	{Touch: 0},
	{Paint_Brush: 0},
	{Bg_Block: 0},
	{AJAX: 0},
	{ArrayBlockColors: 0},
	{ArrayLevel: 0},
	{ArrayCheckBlockColor: 0},
	{Bg: 0},
	{KeyBoard: 0},
	{BlackFade: 0},
	{Cir: 0},
	{Click: 0},
	{start: 0},
	{Drag_SelectLvl: 0},
	{LocalStorege: 0},
	{Rotate: 0},
	{Sine: 0},
	{Sine2: 0},
	{Confetti: 0},
	{P_Confetti: 0},
	{Bg2: 0},
	{Audio: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{F_Buttons_ClickSound: 0},
	{Timer: 0},
	{StopTimer: 0},
	{LayerOpacityWinGO: 0}
];

self.InstanceType = {
	Btn_Home: class extends self.ISpriteInstance {},
	Btn_Info: class extends self.ISpriteInstance {},
	Btn_Levels: class extends self.ISpriteInstance {},
	Btn_lvl: class extends self.ISpriteInstance {},
	Btn_Next_Left: class extends self.ISpriteInstance {},
	Btn_Next_lvl: class extends self.ISpriteInstance {},
	Btn_Next_Right: class extends self.ISpriteInstance {},
	Btn_Restart: class extends self.ISpriteInstance {},
	Btn_Select_LvL: class extends self.ISpriteInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	btn_m: class extends self.ISpriteInstance {},
	txt_lvl_InGame: class extends self.ITextInstance {},
	txt_lvl_Number: class extends self.ITextInstance {},
	txt_lvl_Select: class extends self.ITextInstance {},
	txt_PaintColor: class extends self.ITextInstance {},
	txt_timerBarSecunds: class extends self.ITextInstance {},
	txt_AndGame: class extends self.ITextInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Icon_bgTimer: class extends self.ISpriteInstance {},
	Icon_bgTimer2: class extends self.ISpriteInstance {},
	Icon_Timer: class extends self.ISpriteInstance {},
	Icon_Tutorial: class extends self.ISpriteInstance {},
	Info: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Win: class extends self.ISpriteInstance {},
	Range: class extends self.ISpriteInstance {},
	SmallBackground: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	Brush: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Paint_Brush: class extends self.ISpriteInstance {},
	Bg_Block: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	ArrayBlockColors: class extends self.IArrayInstance {},
	ArrayLevel: class extends self.IArrayInstance {},
	ArrayCheckBlockColor: class extends self.IArrayInstance {},
	Bg: class extends self.ISpriteInstance {},
	KeyBoard: class extends self.IInstance {},
	BlackFade: class extends self.ISpriteInstance {},
	Cir: class extends self.ISpriteInstance {},
	Click: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	Drag_SelectLvl: class extends self.ISpriteInstance {},
	LocalStorege: class extends self.IInstance {},
	Confetti: class extends self.ISpriteInstance {},
	P_Confetti: class extends self.IParticlesInstance {},
	Bg2: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	F_Buttons_ClickSound: class extends self.ISpriteInstance {}
}