const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.rgba255,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.ScriptsInEvents.Game_level_es_Event13_Act3,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.ScriptsInEvents.Game_level_es_Event34_Act3,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.ScriptsInEvents.Game_level_es_Event55_Act1,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.ScriptsInEvents.Mainmenu_es_Event6_Act4,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.ScriptsInEvents.Mainmenu_es_Event7_Act2,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.ScriptsInEvents.Mainmenu_es_Event8_Act2,
		C3.ScriptsInEvents.Mainmenu_es_Event9_Act2,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.ScriptsInEvents.Mainmenu_es_Event10_Act3,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Horizonal2_block: 0},
	{Horizonal3_block: 0},
	{Vertical2_block: 0},
	{Vertical3_block: 0},
	{levelIconValue: 0},
	{Tween: 0},
	{Level_icon: 0},
	{levelTextAsset: 0},
	{left_level_btn: 0},
	{right_level_btn: 0},
	{WinPopup_BG: 0},
	{Down_HomeButton: 0},
	{DownMenu: 0},
	{Down_RestartButton: 0},
	{Down_SoundButton: 0},
	{WinPopup_NextLevelButton: 0},
	{WinPopup_WinDeco: 0},
	{Timer_Progress_bg: 0},
	{Timer_Progress_fg: 0},
	{GameOverPopup_BG: 0},
	{GameOverPopup_Home: 0},
	{GameOverPopup_Restart: 0},
	{blur_bg_popup: 0},
	{WinPopupHomeButton: 0},
	{Down_RestartButton2: 0},
	{WinPopup_Restart: 0},
	{iceAsset: 0},
	{active: 0},
	{MovingPath: 0},
	{BlockType: 0},
	{Physics: 0},
	{Block: 0},
	{Touch: 0},
	{BG_WITH_BORDER: 0},
	{BG_Grid: 0},
	{WinTrigger: 0},
	{WinBlock: 0},
	{GlobalBG: 0},
	{StartButton: 0},
	{LocalStorage: 0},
	{LevelText: 0},
	{Level_ICON_TEXT: 0},
	{menuBgAsset: 0},
	{bg_game: 0},
	{SpriteFont: 0},
	{GameOver_Icon: 0},
	{levelmenu_down_black: 0},
	{Score_Sprite: 0},
	{close_btn: 0},
	{Main_Menu_score_bg: 0},
	{Score_total: 0},
	{Main_menu_GameLogo: 0},
	{Level_score_text: 0},
	{levelTextAsset2: 0},
	{Text: 0},
	{GameOver_text: 0},
	{Audio: 0},
	{Browser: 0},
	{levelSelectionTextAsset: 0},
	{Behind_start_Animation: 0},
	{snowmanAsset: 0},
	{highScoreAsset: 0},
	{GameMonetizeSDK: 0},
	{most_possible_level: 0},
	{level_score: 0},
	{Current_Level: 0},
	{timer_sec: 0},
	{isPlaying: 0},
	{reactivity: 0},
	{touchOffsetX: 0},
	{touchOffsetY: 0},
	{win_reactivity: 0},
	{win_touchOffsetX: 0},
	{win_touchOffsetY: 0},
	{game_score: 0},
	{levelmenu_index: 0},
	{most_level_menu_index: 0},
	{most_level: 0}
];

self.InstanceType = {
	Horizonal2_block: class extends self.ISpriteInstance {},
	Horizonal3_block: class extends self.ISpriteInstance {},
	Vertical2_block: class extends self.ISpriteInstance {},
	Vertical3_block: class extends self.ISpriteInstance {},
	Level_icon: class extends self.ISpriteInstance {},
	levelTextAsset: class extends self.ISpriteInstance {},
	left_level_btn: class extends self.ISpriteInstance {},
	right_level_btn: class extends self.ISpriteInstance {},
	WinPopup_BG: class extends self.ISpriteInstance {},
	Down_HomeButton: class extends self.ISpriteInstance {},
	DownMenu: class extends self.ISpriteInstance {},
	Down_RestartButton: class extends self.ISpriteInstance {},
	Down_SoundButton: class extends self.ISpriteInstance {},
	WinPopup_NextLevelButton: class extends self.ISpriteInstance {},
	WinPopup_WinDeco: class extends self.ISpriteInstance {},
	Timer_Progress_bg: class extends self.ISpriteInstance {},
	Timer_Progress_fg: class extends self.ISpriteInstance {},
	GameOverPopup_BG: class extends self.ISpriteInstance {},
	GameOverPopup_Home: class extends self.ISpriteInstance {},
	GameOverPopup_Restart: class extends self.ISpriteInstance {},
	blur_bg_popup: class extends self.ISpriteInstance {},
	WinPopupHomeButton: class extends self.ISpriteInstance {},
	Down_RestartButton2: class extends self.ISpriteInstance {},
	WinPopup_Restart: class extends self.ISpriteInstance {},
	iceAsset: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	BG_WITH_BORDER: class extends self.ISpriteInstance {},
	BG_Grid: class extends self.ISpriteInstance {},
	WinTrigger: class extends self.ISpriteInstance {},
	WinBlock: class extends self.ISpriteInstance {},
	GlobalBG: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	LevelText: class extends self.ITextInstance {},
	Level_ICON_TEXT: class extends self.ITextInstance {},
	menuBgAsset: class extends self.ISpriteInstance {},
	bg_game: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	GameOver_Icon: class extends self.ISpriteInstance {},
	levelmenu_down_black: class extends self.ISpriteInstance {},
	Score_Sprite: class extends self.ISpriteInstance {},
	close_btn: class extends self.ISpriteInstance {},
	Main_Menu_score_bg: class extends self.ISpriteInstance {},
	Score_total: class extends self.ITextInstance {},
	Main_menu_GameLogo: class extends self.ISpriteInstance {},
	Level_score_text: class extends self.ITextInstance {},
	levelTextAsset2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	GameOver_text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	levelSelectionTextAsset: class extends self.ISpriteInstance {},
	Behind_start_Animation: class extends self.ISpriteInstance {},
	snowmanAsset: class extends self.ISpriteInstance {},
	highScoreAsset: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}