const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Text.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.TouchIndex,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetY,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.projectversion,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Text.Cnds.IsOutsideLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Sine: 0},
	{Sine2: 0},
	{Tween: 0},
	{btn_start: 0},
	{transition: 0},
	{Fade: 0},
	{intro_: 0},
	{progress: 0},
	{Anchor: 0},
	{bottom: 0},
	{anim: 0},
	{Flash: 0},
	{piece: 0},
	{launch: 0},
	{Pin: 0},
	{lineDrag: 0},
	{ok: 0},
	{ani_name: 0},
	{order: 0},
	{last: 0},
	{mark_conect: 0},
	{lineConect: 0},
	{title: 0},
	{areaSelect: 0},
	{lineDraw: 0},
	{directLine: 0},
	{ballUp: 0},
	{pieceMovingeffect: 0},
	{moveAngle: 0},
	{up_effect: 0},
	{a_positions: 0},
	{pos: 0},
	{memPos: 0},
	{txt_info: 0},
	{Keyboard: 0},
	{frame: 0},
	{Timer: 0},
	{txt_score: 0},
	{pointsCount: 0},
	{txt_gameOver: 0},
	{white: 0},
	{txt_point: 0},
	{fade: 0},
	{BGpause: 0},
	{btn_music: 0},
	{btn_sound: 0},
	{btn_main: 0},
	{txt_ver: 0},
	{btn_restart: 0},
	{btn_fullscreen: 0},
	{txt_taptocontinue: 0},
	{txt_reset: 0},
	{btn_info: 0},
	{AJAX: 0},
	{jsonLang: 0},
	{menuActive: 0},
	{txt_btnLanguage: 0},
	{boardLang: 0},
	{colorName: 0},
	{smallSize: 0},
	{music: 0},
	{txt_credits: 0},
	{txt_infoBack: 0},
	{lang: 0},
	{txt_langSelect: 0},
	{bgGame: 0},
	{bgMain: 0},
	{Rotate: 0},
	{snows: 0},
	{p_snowflakes: 0},
	{txt_new: 0},
	{txt_btnBack: 0},
	{pieceShow: 0},
	{newEffect: 0},
	{darBottom: 0},
	{hand: 0},
	{txt_howTo: 0},
	{txt_gotit: 0},
	{screen: 0},
	{explosionEffect: 0},
	{GameMonetizeSDK: 0},
	{TopButtons: 0},
	{positions: 0},
	{AnimationMAX: 0},
	{AnimationMIN: 0},
	{timeToMatchTransition: 0},
	{sequence_typeBallCount: 0},
	{typeBall: 0},
	{highScore: 0},
	{score: 0},
	{hScore: 0},
	{gameStarted: 0},
	{touchStart: 0},
	{par_text: 0},
	{par_sound: 0},
	{count: 0},
	{piece_uid: 0},
	{Parameter0: 0},
	{load_ok: 0},
	{storageName: 0},
	{Sound: 0},
	{rew: 0},
	{Music: 0},
	{fadeTime: 0},
	{in: 0},
	{control: 0},
	{timeAniHowTo: 0},
	{pX: 0},
	{pY: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	btn_start: class extends self.ISpriteInstance {},
	transition: class extends self.ITiledBackgroundInstance {},
	intro_: class extends self.ISpriteInstance {},
	progress: class extends self.ISpriteInstance {},
	bottom: class extends self.ISpriteInstance {},
	piece: class extends self.ISpriteInstance {},
	launch: class extends self.ISpriteInstance {},
	lineDrag: class extends self.ISpriteInstance {},
	mark_conect: class extends self.ISpriteInstance {},
	lineConect: class extends self.ITiledBackgroundInstance {},
	title: class extends self.ISpriteInstance {},
	areaSelect: class extends self.ISpriteInstance {},
	lineDraw: class extends self.ISpriteInstance {},
	directLine: class extends self.ISpriteInstance {},
	ballUp: class extends self.ISpriteInstance {},
	pieceMovingeffect: class extends self.ISpriteInstance {},
	up_effect: class extends self.ISpriteInstance {},
	a_positions: class extends self.IArrayInstance {},
	memPos: class extends self.ISpriteInstance {},
	txt_info: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_gameOver: class extends self.ITextInstance {},
	txt_point: class extends self.ITextInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	BGpause: class extends self.ITiledBackgroundInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_main: class extends self.ISpriteInstance {},
	txt_ver: class extends self.ITextInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_fullscreen: class extends self.ISpriteInstance {},
	txt_taptocontinue: class extends self.ITextInstance {},
	txt_reset: class extends self.ITextInstance {},
	btn_info: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	jsonLang: class extends self.IJSONInstance {},
	txt_btnLanguage: class extends self.ITextInstance {},
	boardLang: class extends self.ISpriteInstance {},
	txt_credits: class extends self.ITextInstance {},
	txt_infoBack: class extends self.ITextInstance {},
	txt_langSelect: class extends self.ITextInstance {},
	bgGame: class extends self.ISpriteInstance {},
	bgMain: class extends self.ISpriteInstance {},
	snows: class extends self.ISpriteInstance {},
	p_snowflakes: class extends self.IParticlesInstance {},
	txt_new: class extends self.ITextInstance {},
	txt_btnBack: class extends self.ITextInstance {},
	pieceShow: class extends self.ISpriteInstance {},
	newEffect: class extends self.ISpriteInstance {},
	darBottom: class extends self.ITiledBackgroundInstance {},
	hand: class extends self.ISpriteInstance {},
	txt_howTo: class extends self.ITextInstance {},
	txt_gotit: class extends self.ITextInstance {},
	screen: class extends self.ISpriteInstance {},
	explosionEffect: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	TopButtons: class extends self.ISpriteInstance {}
}