const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Plugins.Timeline,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Behaviors.MoveTo,
		C3.Behaviors.bound,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{area: 0},
	{active: 0},
	{mask: 0},
	{DragDrop: 0},
	{Tween: 0},
	{rectangle: 0},
	{triangle: 0},
	{cilinder: 0},
	{wholeRectangle: 0},
	{wholeTriangle: 0},
	{wholeCilinder: 0},
	{wallLeft: 0},
	{wallRight: 0},
	{lock: 0},
	{prickleLeft: 0},
	{prickleRight: 0},
	{Touch: 0},
	{touchCilinder: 0},
	{touchRectangle: 0},
	{touchTriangle: 0},
	{blikEnemy: 0},
	{triangleMask: 0},
	{rectangleMask: 0},
	{cilinderMask: 0},
	{effectRectangle: 0},
	{effectTriangle: 0},
	{effectCilinder: 0},
	{destroyParticles: 0},
	{winCilinder: 0},
	{winRectangle: 0},
	{winTriangle: 0},
	{Fade: 0},
	{wineffect: 0},
	{effectDamage: 0},
	{effectWin: 0},
	{damageParticles: 0},
	{winParticles: 0},
	{dot: 0},
	{Score: 0},
	{loseEffect: 0},
	{startEffect: 0},
	{logo: 0},
	{play: 0},
	{playShadow: 0},
	{textPlay: 0},
	{Timeline: 0},
	{particlesPlay: 0},
	{particlesPlay2: 0},
	{home: 0},
	{LocalStorage: 0},
	{textBest: 0},
	{BestScore: 0},
	{Audio: 0},
	{www: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{AllWhole: 0},
	{MoveTo: 0},
	{EnemySet: 0},
	{BoundToLayout: 0},
	{AllFigures: 0},
	{FiguresMask: 0},
	{Win: 0},
	{SpeedEnemy: 0},
	{HighScore: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	area: class extends self.ISpriteInstance {},
	rectangle: class extends self.ISpriteInstance {},
	triangle: class extends self.ISpriteInstance {},
	cilinder: class extends self.ISpriteInstance {},
	wholeRectangle: class extends self.ISpriteInstance {},
	wholeTriangle: class extends self.ISpriteInstance {},
	wholeCilinder: class extends self.ISpriteInstance {},
	wallLeft: class extends self.ISpriteInstance {},
	wallRight: class extends self.ISpriteInstance {},
	lock: class extends self.ISpriteInstance {},
	prickleLeft: class extends self.ISpriteInstance {},
	prickleRight: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	touchCilinder: class extends self.ISpriteInstance {},
	touchRectangle: class extends self.ISpriteInstance {},
	touchTriangle: class extends self.ISpriteInstance {},
	blikEnemy: class extends self.ISpriteInstance {},
	triangleMask: class extends self.ISpriteInstance {},
	rectangleMask: class extends self.ISpriteInstance {},
	cilinderMask: class extends self.ISpriteInstance {},
	effectRectangle: class extends self.ISpriteInstance {},
	effectTriangle: class extends self.ISpriteInstance {},
	effectCilinder: class extends self.ISpriteInstance {},
	destroyParticles: class extends self.IParticlesInstance {},
	winCilinder: class extends self.ISpriteInstance {},
	winRectangle: class extends self.ISpriteInstance {},
	winTriangle: class extends self.ISpriteInstance {},
	wineffect: class extends self.ISpriteInstance {},
	effectDamage: class extends self.ISpriteInstance {},
	effectWin: class extends self.ISpriteInstance {},
	damageParticles: class extends self.IParticlesInstance {},
	winParticles: class extends self.IParticlesInstance {},
	dot: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteFontInstance {},
	loseEffect: class extends self.ITiledBackgroundInstance {},
	startEffect: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	playShadow: class extends self.ISpriteInstance {},
	textPlay: class extends self.ISpriteFontInstance {},
	mask: class extends self.ISpriteInstance {},
	Timeline: class extends self.IInstance {},
	particlesPlay: class extends self.IParticlesInstance {},
	particlesPlay2: class extends self.IParticlesInstance {},
	home: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	textBest: class extends self.ISpriteFontInstance {},
	BestScore: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	www: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	AllWhole: class extends self.ISpriteInstance {},
	EnemySet: class extends self.ISpriteInstance {},
	AllFigures: class extends self.ISpriteInstance {},
	FiguresMask: class extends self.ISpriteInstance {}
}