const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.WGSDK,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Text.Exps.Count,
		C3.Plugins.Text.Cnds.CompareX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{LocalStorege: 0},
	{Mouse: 0},
	{Touch: 0},
	{Browse: 0},
	{Audio: 0},
	{Subtract: 0},
	{Tween: 0},
	{Ball_Blue: 0},
	{Touched: 0},
	{OverlappingPoint: 0},
	{Ball_Player: 0},
	{Fade: 0},
	{Balltouched: 0},
	{Bg: 0},
	{P_Star: 0},
	{Busy: 0},
	{Point: 0},
	{PointNeon: 0},
	{PointNeonS: 0},
	{Shadow_Blue: 0},
	{Shadow_Blue2: 0},
	{Shadow_Player: 0},
	{ID: 0},
	{aCount: 0},
	{icon_move: 0},
	{Btn_lvl: 0},
	{Btn_Reset: 0},
	{Btn_Sound: 0},
	{FadeWin: 0},
	{P_Btn: 0},
	{Framelvl: 0},
	{Btn_Left: 0},
	{Btn_Right: 0},
	{Sine: 0},
	{Finger: 0},
	{Padlock: 0},
	{BtnPlay: 0},
	{Btn_Back: 0},
	{txt_lvlgame: 0},
	{txt_move: 0},
	{txt_nice: 0},
	{Number: 0},
	{txt_selectlvl: 0},
	{txt_tutorial: 0},
	{txt_lvlgame2: 0},
	{InserirUmTítulo: 0},
	{btn_more: 0},
	{btn_more_in: 0},
	{WeeGooSDK: 0},
	{btn_skip: 0},
	{skip_txt: 0},
	{GameMonetizeSDK: 0},
	{F_Btns: 0},
	{Moves: 0},
	{PointFrame0: 0},
	{Brek: 0},
	{OverlPointBlue: 0},
	{Position: 0},
	{LvLinFrame: 0},
	{Current_Level: 0},
	{Completed_Level: 0},
	{Trigger: 0},
	{Sound: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	LocalStorege: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Ball_Blue: class extends self.ISpriteInstance {},
	Ball_Player: class extends self.ISpriteInstance {},
	Balltouched: class extends self.ISpriteInstance {},
	Bg: class extends self.ISpriteInstance {},
	P_Star: class extends self.IParticlesInstance {},
	Point: class extends self.ISpriteInstance {},
	PointNeon: class extends self.ISpriteInstance {},
	PointNeonS: class extends self.ISpriteInstance {},
	Shadow_Blue: class extends self.ISpriteInstance {},
	Shadow_Blue2: class extends self.ISpriteInstance {},
	Shadow_Player: class extends self.ISpriteInstance {},
	icon_move: class extends self.ISpriteInstance {},
	Btn_lvl: class extends self.ISpriteInstance {},
	Btn_Reset: class extends self.ISpriteInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	FadeWin: class extends self.ISpriteInstance {},
	P_Btn: class extends self.IParticlesInstance {},
	Framelvl: class extends self.ISpriteInstance {},
	Btn_Left: class extends self.ISpriteInstance {},
	Btn_Right: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	Padlock: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	Btn_Back: class extends self.ISpriteInstance {},
	txt_lvlgame: class extends self.ITextInstance {},
	txt_move: class extends self.ITextInstance {},
	txt_nice: class extends self.ITextInstance {},
	txt_selectlvl: class extends self.ITextInstance {},
	txt_tutorial: class extends self.ITextInstance {},
	txt_lvlgame2: class extends self.ITextInstance {},
	InserirUmTítulo: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	btn_more_in: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	btn_skip: class extends self.ISpriteInstance {},
	skip_txt: class extends self.ITextInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	F_Btns: class extends self.ISpriteInstance {}
}