const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{LocalStorage: 0},
	{GameData: 0},
	{SwapData: 0},
	{Touch: 0},
	{ArrayTemp2: 0},
	{array_level: 0},
	{Browser: 0},
	{Keyboard: 0},
	{AJAX: 0},
	{array_save: 0},
	{array_map_temp: 0},
	{QuitBTN: 0},
	{Anchor: 0},
	{PauseBTN: 0},
	{MoreGamesBTN: 0},
	{RestartBTN: 0},
	{ContinueBTN: 0},
	{SoundBTN: 0},
	{CloseBTN: 0},
	{PlayBTN: 0},
	{ScrollBTN: 0},
	{BackBTN: 0},
	{TapBTN: 0},
	{level: 0},
	{LevelsBTN: 0},
	{StartBTN: 0},
	{NoBTN: 0},
	{YesBTN: 0},
	{BombEffect: 0},
	{Tween: 0},
	{BonusText: 0},
	{type: 0},
	{CheckUI: 0},
	{CompanyLogo: 0},
	{DarkBackground: 0},
	{Seno: 0},
	{Seno2: 0},
	{DogBody: 0},
	{DogHead: 0},
	{GameBackground: 0},
	{GameHeaderUI: 0},
	{row: 0},
	{col: 0},
	{Moving: 0},
	{TargetY: 0},
	{RedFoc: 0},
	{Swap: 0},
	{isMatch: 0},
	{Trigger: 0},
	{GameItem: 0},
	{GameItemInitial: 0},
	{GameItemTween: 0},
	{GameItemUI: 0},
	{GameOverUI: 0},
	{GameTiles: 0},
	{Sine: 0},
	{GameTittle: 0},
	{GetReadyUI: 0},
	{GrassOutline: 0},
	{Pin: 0},
	{Fade: 0},
	{LevelButtonFont: 0},
	{LevelCompleteParticles: 0},
	{Girar: 0},
	{LevelCompleteSpin: 0},
	{LevelCompleteStar: 0},
	{LevelFont: 0},
	{LevelParticles: 0},
	{LevelPointer: 0},
	{LevelUI: 0},
	{LivesHeaderUI: 0},
	{LiveTaken: 0},
	{Rotate: 0},
	{LoadingAnimation: 0},
	{MapBackground: 0},
	{ScrollTo: 0},
	{MapCamera: 0},
	{MapGrass: 0},
	{MapHouse1: 0},
	{MapHouse2: 0},
	{MapShadow: 0},
	{MapTree: 0},
	{MapWater: 0},
	{MapWater2: 0},
	{MatchEffect1: 0},
	{MatchEffect2: 0},
	{MatchWoodParticles: 0},
	{MenuBackground: 0},
	{MenuTree1: 0},
	{MenuTree2: 0},
	{MenuTree3: 0},
	{MenuTree4: 0},
	{MenuTree5: 0},
	{MenuTree6: 0},
	{MovesFont: 0},
	{NoMoreLivesUI: 0},
	{Power1: 0},
	{Power2: 0},
	{Power3: 0},
	{Power4: 0},
	{PowerEffectv1: 0},
	{PowerEffectv2: 0},
	{PowerEffectv3: 0},
	{PowerEffectv4: 0},
	{PowerParticles: 0},
	{Desvanecer: 0},
	{PowerUpsBackground: 0},
	{power: 0},
	{PowerUPSFont: 0},
	{PowerUpsHeaderUI: 0},
	{PowerUpsUI: 0},
	{SpriteFont: 0},
	{TargetFont: 0},
	{TittleFlower: 0},
	{TittleLeaves: 0},
	{WellDoneUI: 0},
	{WoodFrame: 0},
	{WoodFrame2: 0},
	{WoodFrame3: 0},
	{WoodMenu: 0},
	{FadeScreen: 0},
	{RstBTN2: 0},
	{GameMonetizeSDK: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Buttons: 0},
	{score: 0},
	{combos: 0},
	{game_mode: 0},
	{max_color: 0},
	{state: 0},
	{width: 0},
	{height: 0},
	{PosX: 0},
	{PosY: 0},
	{tile_size: 0},
	{fall_speed: 0},
	{is_falling: 0},
	{draging: 0},
	{top_cell: 0},
	{match_count: 0},
	{cur_level: 0},
	{cur_moves: 0},
	{moves: 0},
	{value1: 0},
	{value2: 0},
	{redfoc: 0},
	{frame: 0},
	{uid: 0},
	{shift: 0},
	{shift2: 0},
	{cur: 0},
	{Touching: 0},
	{NotMatch: 0},
	{value: 0},
	{plus: 0},
	{substract: 0},
	{ScoreTemp: 0},
	{ScoreTemp2: 0},
	{origin_x: 0},
	{origin_y: 0},
	{end_x: 0},
	{end_y: 0},
	{UsingPower: 0},
	{P2trigger: 0},
	{music: 0},
	{sound: 0},
	{name: 0},
	{total_level: 0},
	{unlocked_level: 0},
	{cur_page: 0},
	{end_y_of_level: 0},
	{bg_map_size: 0},
	{lvl_btns_per_screen: 0},
	{scroll_min_y: 0},
	{scroll_max_y: 0},
	{Lives: 0},
	{index: 0},
	{initial_bg_map_y: 0},
	{map_multiplier: 0},
	{pos_y: 0},
	{pos_x: 0},
	{step_move: 0},
	{direction: 0},
	{Target1: 0},
	{Target2: 0},
	{Target3: 0},
	{x: 0},
	{y: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	GameData: class extends self.IArrayInstance {},
	SwapData: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	ArrayTemp2: class extends self.IArrayInstance {},
	array_level: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	array_save: class extends self.IArrayInstance {},
	array_map_temp: class extends self.IArrayInstance {},
	QuitBTN: class extends self.ISpriteInstance {},
	PauseBTN: class extends self.ISpriteInstance {},
	MoreGamesBTN: class extends self.ISpriteInstance {},
	RestartBTN: class extends self.ISpriteInstance {},
	ContinueBTN: class extends self.ISpriteInstance {},
	SoundBTN: class extends self.ISpriteInstance {},
	CloseBTN: class extends self.ISpriteInstance {},
	PlayBTN: class extends self.ISpriteInstance {},
	ScrollBTN: class extends self.ISpriteInstance {},
	BackBTN: class extends self.ISpriteInstance {},
	TapBTN: class extends self.ISpriteInstance {},
	LevelsBTN: class extends self.ISpriteInstance {},
	StartBTN: class extends self.ISpriteInstance {},
	NoBTN: class extends self.ISpriteInstance {},
	YesBTN: class extends self.ISpriteInstance {},
	BombEffect: class extends self.ISpriteInstance {},
	BonusText: class extends self.ISpriteInstance {},
	CheckUI: class extends self.ISpriteInstance {},
	CompanyLogo: class extends self.ISpriteInstance {},
	DarkBackground: class extends self.ITiledBackgroundInstance {},
	DogBody: class extends self.ISpriteInstance {},
	DogHead: class extends self.ISpriteInstance {},
	GameBackground: class extends self.ISpriteInstance {},
	GameHeaderUI: class extends self.ISpriteInstance {},
	GameItem: class extends self.ISpriteInstance {},
	GameItemInitial: class extends self.ISpriteInstance {},
	GameItemTween: class extends self.ISpriteInstance {},
	GameItemUI: class extends self.ISpriteInstance {},
	GameOverUI: class extends self.ISpriteInstance {},
	GameTiles: class extends self.ISpriteInstance {},
	GameTittle: class extends self.ISpriteInstance {},
	GetReadyUI: class extends self.ISpriteInstance {},
	GrassOutline: class extends self.ISpriteInstance {},
	LevelButtonFont: class extends self.ISpriteFontInstance {},
	LevelCompleteParticles: class extends self.IParticlesInstance {},
	LevelCompleteSpin: class extends self.ISpriteInstance {},
	LevelCompleteStar: class extends self.ISpriteInstance {},
	LevelFont: class extends self.ISpriteFontInstance {},
	LevelParticles: class extends self.IParticlesInstance {},
	LevelPointer: class extends self.ISpriteInstance {},
	LevelUI: class extends self.ISpriteInstance {},
	LivesHeaderUI: class extends self.ISpriteInstance {},
	LiveTaken: class extends self.ISpriteInstance {},
	LoadingAnimation: class extends self.ISpriteInstance {},
	MapBackground: class extends self.ISpriteInstance {},
	MapCamera: class extends self.ISpriteInstance {},
	MapGrass: class extends self.ISpriteInstance {},
	MapHouse1: class extends self.ISpriteInstance {},
	MapHouse2: class extends self.ISpriteInstance {},
	MapShadow: class extends self.ISpriteInstance {},
	MapTree: class extends self.ISpriteInstance {},
	MapWater: class extends self.ISpriteInstance {},
	MapWater2: class extends self.ISpriteInstance {},
	MatchEffect1: class extends self.ISpriteInstance {},
	MatchEffect2: class extends self.ISpriteInstance {},
	MatchWoodParticles: class extends self.IParticlesInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	MenuTree1: class extends self.ISpriteInstance {},
	MenuTree2: class extends self.ISpriteInstance {},
	MenuTree3: class extends self.ISpriteInstance {},
	MenuTree4: class extends self.ISpriteInstance {},
	MenuTree5: class extends self.ISpriteInstance {},
	MenuTree6: class extends self.ISpriteInstance {},
	MovesFont: class extends self.ISpriteFontInstance {},
	NoMoreLivesUI: class extends self.ISpriteInstance {},
	Power1: class extends self.ISpriteInstance {},
	Power2: class extends self.ISpriteInstance {},
	Power3: class extends self.ISpriteInstance {},
	Power4: class extends self.ISpriteInstance {},
	PowerEffectv1: class extends self.ISpriteInstance {},
	PowerEffectv2: class extends self.ISpriteInstance {},
	PowerEffectv3: class extends self.ISpriteInstance {},
	PowerEffectv4: class extends self.ISpriteInstance {},
	PowerParticles: class extends self.IParticlesInstance {},
	PowerUpsBackground: class extends self.ITiledBackgroundInstance {},
	PowerUPSFont: class extends self.ISpriteFontInstance {},
	PowerUpsHeaderUI: class extends self.ISpriteInstance {},
	PowerUpsUI: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	TargetFont: class extends self.ISpriteFontInstance {},
	TittleFlower: class extends self.ISpriteInstance {},
	TittleLeaves: class extends self.ISpriteInstance {},
	WellDoneUI: class extends self.ISpriteInstance {},
	WoodFrame: class extends self.ISpriteInstance {},
	WoodFrame2: class extends self.ISpriteInstance {},
	WoodFrame3: class extends self.ISpriteInstance {},
	WoodMenu: class extends self.ISpriteInstance {},
	FadeScreen: class extends self.ISpriteInstance {},
	RstBTN2: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}