const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{GamePlayBG: 0},
	{MenuBG: 0},
	{GameTypeBG: 0},
	{learningBG: 0},
	{Sine: 0},
	{PlayButton: 0},
	{Sound: 0},
	{homeButton: 0},
	{leftButton: 0},
	{rightButton: 0},
	{Touch: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{LearningOpt: 0},
	{GPlayOpt: 0},
	{Tween: 0},
	{Flash: 0},
	{Sine2: 0},
	{option1: 0},
	{Gplayobject: 0},
	{Sprite: 0},
	{option2: 0},
	{option3: 0},
	{option4: 0},
	{option5: 0},
	{option6: 0},
	{option7: 0},
	{option8: 0},
	{option9: 0},
	{option10: 0},
	{option11: 0},
	{option12: 0},
	{option13: 0},
	{option14: 0},
	{option15: 0},
	{option16: 0},
	{option17: 0},
	{option18: 0},
	{option19: 0},
	{option20: 0},
	{option21: 0},
	{option22: 0},
	{option23: 0},
	{option24: 0},
	{option25: 0},
	{option26: 0},
	{option27: 0},
	{option28: 0},
	{option29: 0},
	{option30: 0},
	{fade: 0},
	{FLOWER: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TOOL: 0}
];

self.InstanceType = {
	GamePlayBG: class extends self.ISpriteInstance {},
	MenuBG: class extends self.ISpriteInstance {},
	GameTypeBG: class extends self.ISpriteInstance {},
	learningBG: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	Sound: class extends self.ISpriteInstance {},
	homeButton: class extends self.ISpriteInstance {},
	leftButton: class extends self.ISpriteInstance {},
	rightButton: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	LearningOpt: class extends self.ISpriteInstance {},
	GPlayOpt: class extends self.ISpriteInstance {},
	option1: class extends self.ISpriteInstance {},
	Gplayobject: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	option2: class extends self.ISpriteInstance {},
	option3: class extends self.ISpriteInstance {},
	option4: class extends self.ISpriteInstance {},
	option5: class extends self.ISpriteInstance {},
	option6: class extends self.ISpriteInstance {},
	option7: class extends self.ISpriteInstance {},
	option8: class extends self.ISpriteInstance {},
	option9: class extends self.ISpriteInstance {},
	option10: class extends self.ISpriteInstance {},
	option11: class extends self.ISpriteInstance {},
	option12: class extends self.ISpriteInstance {},
	option13: class extends self.ISpriteInstance {},
	option14: class extends self.ISpriteInstance {},
	option15: class extends self.ISpriteInstance {},
	option16: class extends self.ISpriteInstance {},
	option17: class extends self.ISpriteInstance {},
	option18: class extends self.ISpriteInstance {},
	option19: class extends self.ISpriteInstance {},
	option20: class extends self.ISpriteInstance {},
	option21: class extends self.ISpriteInstance {},
	option22: class extends self.ISpriteInstance {},
	option23: class extends self.ISpriteInstance {},
	option24: class extends self.ISpriteInstance {},
	option25: class extends self.ISpriteInstance {},
	option26: class extends self.ISpriteInstance {},
	option27: class extends self.ISpriteInstance {},
	option28: class extends self.ISpriteInstance {},
	option29: class extends self.ISpriteInstance {},
	option30: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	FLOWER: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TOOL: class extends self.ISpriteInstance {}
}