const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.MoveTo.Exps.MaxSpeed,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject
	];
};
self.C3_JsPropNameTable = [
	{CarSprite: 0},
	{Keyboard: 0},
	{waypoints: 0},
	{amtWaypoints: 0},
	{MoveTo: 0},
	{Tween: 0},
	{Timer: 0},
	{CarBase: 0},
	{Background: 0},
	{waypointID: 0},
	{CarWaypoint: 0},
	{parentUID: 0},
	{CarArea: 0},
	{Touch: 0},
	{Sine: 0},
	{SignSprite: 0},
	{TextTutorial: 0},
	{Fader: 0},
	{Solid: 0},
	{EndOfRoute: 0},
	{TextRetry: 0},
	{Fade: 0},
	{TextWin: 0},
	{TireMarks: 0},
	{CarBrakeArea: 0},
	{LightPosts: 0},
	{Smoke: 0},
	{Screenshot_: 0},
	{btn_playsheet: 0},
	{gameover: 0},
	{try: 0},
	{Audio: 0},
	{GameMonetizeSDK: 0},
	{carMoving: 0}
];

self.InstanceType = {
	CarSprite: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	CarBase: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	CarWaypoint: class extends self.ISpriteInstance {},
	CarArea: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	SignSprite: class extends self.ISpriteInstance {},
	TextTutorial: class extends self.ITextInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	EndOfRoute: class extends self.ISpriteInstance {},
	TextRetry: class extends self.ITextInstance {},
	TextWin: class extends self.ITextInstance {},
	TireMarks: class extends self.ISpriteInstance {},
	CarBrakeArea: class extends self.ISpriteInstance {},
	LightPosts: class extends self.ISpriteInstance {},
	Smoke: class extends self.IParticlesInstance {},
	Screenshot_: class extends self.ISpriteInstance {},
	btn_playsheet: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	try: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}