const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Tween: 0},
	{Tile: 0},
	{PlayerTile: 0},
	{PlayerCollider: 0},
	{TileOrderArr: 0},
	{Keyboard: 0},
	{OldTile: 0},
	{ColorsArr: 0},
	{AJAX: 0},
	{Touch: 0},
	{TextScore: 0},
	{lifeID: 0},
	{Rotate: 0},
	{Life: 0},
	{Fader: 0},
	{TextTutorial: 0},
	{TextGameOver: 0},
	{Background: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Audio: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{GameMonetizeSDK: 0},
	{PERIODREDUCTION: 0},
	{MINIMUMPERIOD: 0},
	{currentPeriod: 0},
	{lives: 0},
	{score: 0},
	{randomColorID: 0},
	{periodOffset: 0},
	{period: 0},
	{correctTileUID: 0},
	{correct: 0},
	{sound: 0}
];

self.InstanceType = {
	Tile: class extends self.ISpriteInstance {},
	PlayerTile: class extends self.ISpriteInstance {},
	PlayerCollider: class extends self.ISpriteInstance {},
	TileOrderArr: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	OldTile: class extends self.ISpriteInstance {},
	ColorsArr: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	TextScore: class extends self.ITextInstance {},
	Life: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTutorial: class extends self.ITextInstance {},
	TextGameOver: class extends self.ITextInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}