const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Sine: 0},
	{Fruit: 0},
	{Shadow1: 0},
	{Shadow2: 0},
	{Shadow3: 0},
	{Score: 0},
	{Touch: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{sound: 0},
	{pause: 0},
	{Audio: 0},
	{broad: 0},
	{Sprite10: 0},
	{home: 0},
	{retry: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{ProgressBar: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{LocalStorage: 0},
	{txt_high_score: 0},
	{Sprite13: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Particles: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{CurrentFruit: 0},
	{CorrectShadow: 0},
	{TimeLeft: 0},
	{highScore: 0}
];

self.InstanceType = {
	Fruit: class extends self.ISpriteInstance {},
	Shadow1: class extends self.ISpriteInstance {},
	Shadow2: class extends self.ISpriteInstance {},
	Shadow3: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	broad: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	txt_high_score: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}