const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Function,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Behaviors.DragnDrop,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Share,
		C3.Plugins.Button,
		C3.Plugins.GM_SDK,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Share.Cnds.IsSharingFilesSupported,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.Share.Acts.AddFile,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Pencil: 0},
	{Canvas: 0},
	{btn_back: 0},
	{btn_camera: 0},
	{Canvas_Thumbnail: 0},
	{Touch: 0},
	{Brush_Color: 0},
	{Touchpoint: 0},
	{Frame: 0},
	{Show_Brush_Size: 0},
	{Browser: 0},
	{Text: 0},
	{Function: 0},
	{BG_Table: 0},
	{Game_Title: 0},
	{selectscreen: 0},
	{bt_Blankpage: 0},
	{Border: 0},
	{Sine: 0},
	{Mini_BG: 0},
	{restart: 0},
	{Sprite: 0},
	{play: 0},
	{videoigrice: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{trokut: 0},
	{Sprite8: 0},
	{knjiga: 0},
	{Sprite11: 0},
	{Sprite2: 0},
	{Sprite12: 0},
	{selectscreen2: 0},
	{olovka: 0},
	{Sprite14: 0},
	{olovka1: 0},
	{zvuk: 0},
	{zvuk1: 0},
	{Sprite3: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{zoomin: 0},
	{zoomout: 0},
	{Sprite19: 0},
	{Sprite22: 0},
	{Mouse: 0},
	{Sprite6: 0},
	{DragDrop: 0},
	{stamp: 0},
	{Sprite7: 0},
	{ruka: 0},
	{sharebtn: 0},
	{AJAX: 0},
	{BinaryData: 0},
	{ScreenshotSprite: 0},
	{sharebtn2: 0},
	{Share: 0},
	{ShareButton: 0},
	{DownloadButton: 0},
	{btn_camera2: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite13: 0},
	{Mini_BG2: 0},
	{Mini_BG3: 0},
	{Mini_BG4: 0},
	{Mini_BG5: 0},
	{Sprite15: 0},
	{Sprite20: 0},
	{GameMonetizeSDK: 0},
	{Sprite21: 0},
	{prva: 0},
	{druga: 0},
	{Sprite23: 0},
	{treca: 0},
	{Sprite24: 0},
	{cetvrta: 0},
	{ToolTip: 0},
	{Pin: 0},
	{Snow: 0},
	{Family: 0},
	{dugmad: 0},
	{PenUID: 0},
	{y_position: 0},
	{x_position: 0},
	{Menu_layers: 0},
	{Set_Color_Frame: 0},
	{Brush_Size: 0},
	{Canvas_Image_Frame: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Pencil: class extends self.ISpriteInstance {},
	Canvas: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_camera: class extends self.ISpriteInstance {},
	Canvas_Thumbnail: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Brush_Color: class extends self.ISpriteInstance {},
	Touchpoint: class extends self.ISpriteInstance {},
	Show_Brush_Size: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Function: class extends self.IInstance {},
	BG_Table: class extends self.ISpriteInstance {},
	Game_Title: class extends self.ISpriteInstance {},
	selectscreen: class extends self.ISpriteInstance {},
	bt_Blankpage: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	Mini_BG: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	videoigrice: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	trokut: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	knjiga: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	selectscreen2: class extends self.ISpriteInstance {},
	olovka: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	olovka1: class extends self.ISpriteInstance {},
	zvuk: class extends self.ISpriteInstance {},
	zvuk1: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	zoomin: class extends self.ISpriteInstance {},
	zoomout: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	stamp: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	sharebtn: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	ScreenshotSprite: class extends self.ISpriteInstance {},
	sharebtn2: class extends self.ISpriteInstance {},
	Share: class extends self.IInstance {},
	ShareButton: class extends self.IButtonInstance {},
	DownloadButton: class extends self.IButtonInstance {},
	btn_camera2: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Mini_BG2: class extends self.ISpriteInstance {},
	Mini_BG3: class extends self.ISpriteInstance {},
	Mini_BG4: class extends self.ISpriteInstance {},
	Mini_BG5: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	prva: class extends self.ISpriteInstance {},
	druga: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	treca: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	cetvrta: class extends self.ISpriteInstance {},
	Snow: class extends self.IParticlesInstance {},
	Family: class extends self.ISpriteInstance {},
	dugmad: class extends self.ISpriteInstance {}
}