const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.ScriptsInEvents.Game_es_Event22_Act5,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.ScriptsInEvents.Game_es_Event43_Act1,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.ScriptsInEvents.Game_es_Event46_Act1,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{"10_Jackfruit": 0},
	{"11_Lime": 0},
	{fruit_type: 0},
	{Tween: 0},
	{"01_apple": 0},
	{"02_orange": 0},
	{"03_melon": 0},
	{"04_coco": 0},
	{"05_Banana": 0},
	{"06_Strawberry": 0},
	{"07_Avocado": 0},
	{"08_Mango": 0},
	{"09_Pineapple": 0},
	{Final_Lime: 0},
	{DragDrop: 0},
	{pipe: 0},
	{Keyboard: 0},
	{ground: 0},
	{ScrollTo: 0},
	{Game_BG: 0},
	{hitcheck: 0},
	{MainMenu_BG: 0},
	{Play_btn: 0},
	{Mouse: 0},
	{Settings_btn: 0},
	{Settings_Menu_BG: 0},
	{Settings_btn_to_home: 0},
	{Settings_btn_resume: 0},
	{ScoreText: 0},
	{GameOver_Menu_BG: 0},
	{GameOver_btn_to_home: 0},
	{GameOver_btn_Restart: 0},
	{ScoreText_Text: 0},
	{NextHint: 0},
	{any_bg_800: 0},
	{popup_bg_overlay: 0},
	{Touch: 0},
	{pipe_right_btn: 0},
	{pipe_left_btn: 0},
	{BGAudio: 0},
	{Settings_btn_sound: 0},
	{pipe_indicator: 0},
	{HitcheckIndicator: 0},
	{RV_ad_popup_BG: 0},
	{RV_ad_popup_Watch: 0},
	{RV_ad_popup_Skip: 0},
	{PipeParticles: 0},
	{EmojiBlush_Icon: 0},
	{Settings_btn_Paused_text: 0},
	{wall: 0},
	{LocalStorage: 0},
	{MainMenu_Score_BG: 0},
	{MainMenu_Score_Label: 0},
	{HighScore_view: 0},
	{MainMenu_btn_sound: 0},
	{GameMonetizeSDK: 0},
	{emit_fruit_num: 0},
	{can_emit: 0},
	{paused: 0},
	{game_score: 0},
	{next_element_radius: 0},
	{max_emit_random: 0},
	{rv_ad_enabled: 0},
	{rv_popup: 0},
	{no_session: 0},
	{playable: 0}
];

self.InstanceType = {
	_10_Jackfruit: class extends self.ISpriteInstance {},
	_11_Lime: class extends self.ISpriteInstance {},
	_01_apple: class extends self.ISpriteInstance {},
	_02_orange: class extends self.ISpriteInstance {},
	_03_melon: class extends self.ISpriteInstance {},
	_04_coco: class extends self.ISpriteInstance {},
	_05_Banana: class extends self.ISpriteInstance {},
	_06_Strawberry: class extends self.ISpriteInstance {},
	_07_Avocado: class extends self.ISpriteInstance {},
	_08_Mango: class extends self.ISpriteInstance {},
	_09_Pineapple: class extends self.ISpriteInstance {},
	Final_Lime: class extends self.ISpriteInstance {},
	pipe: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	ground: class extends self.ISpriteInstance {},
	Game_BG: class extends self.ISpriteInstance {},
	hitcheck: class extends self.ISpriteInstance {},
	MainMenu_BG: class extends self.ISpriteInstance {},
	Play_btn: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Settings_btn: class extends self.ISpriteInstance {},
	Settings_Menu_BG: class extends self.ISpriteInstance {},
	Settings_btn_to_home: class extends self.ISpriteInstance {},
	Settings_btn_resume: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	GameOver_Menu_BG: class extends self.ISpriteInstance {},
	GameOver_btn_to_home: class extends self.ISpriteInstance {},
	GameOver_btn_Restart: class extends self.ISpriteInstance {},
	ScoreText_Text: class extends self.ITextInstance {},
	NextHint: class extends self.ISpriteInstance {},
	any_bg_800: class extends self.ISpriteInstance {},
	popup_bg_overlay: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	pipe_right_btn: class extends self.ISpriteInstance {},
	pipe_left_btn: class extends self.ISpriteInstance {},
	BGAudio: class extends self.IInstance {},
	Settings_btn_sound: class extends self.ISpriteInstance {},
	pipe_indicator: class extends self.ISpriteInstance {},
	HitcheckIndicator: class extends self.ISpriteInstance {},
	RV_ad_popup_BG: class extends self.ISpriteInstance {},
	RV_ad_popup_Watch: class extends self.ISpriteInstance {},
	RV_ad_popup_Skip: class extends self.ISpriteInstance {},
	PipeParticles: class extends self.IParticlesInstance {},
	EmojiBlush_Icon: class extends self.ISpriteInstance {},
	Settings_btn_Paused_text: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	MainMenu_Score_BG: class extends self.ISpriteInstance {},
	MainMenu_Score_Label: class extends self.ISpriteInstance {},
	HighScore_view: class extends self.ITextInstance {},
	MainMenu_btn_sound: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}