const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.Persist,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{BtnPlay: 0},
	{PaintingNotebook: 0},
	{Fade: 0},
	{Images: 0},
	{Touch: 0},
	{WhiteEdge: 0},
	{Brush: 0},
	{BrushColor: 0},
	{BrushSize: 0},
	{BtnCamera: 0},
	{Browser: 0},
	{BtnHome: 0},
	{Sine: 0},
	{title0: 0},
	{Sound: 0},
	{BtnSound: 0},
	{BrushMark: 0},
	{TableExit: 0},
	{BtnPrintExit: 0},
	{BtnExit: 0},
	{BtnClose: 0},
	{Eraser: 0},
	{BtnNextImages: 0},
	{OpacityExit: 0},
	{Background: 0},
	{List: 0},
	{TableUI: 0},
	{BrushSizeAux: 0},
	{NKGurl: 0},
	{btn_more: 0},
	{ch1: 0},
	{Pin: 0},
	{Persist: 0},
	{FireSparkParticlesMenu: 0},
	{Bullet: 0},
	{sky: 0},
	{ch2: 0},
	{btn_more_main: 0},
	{btn_home: 0},
	{pos0: 0},
	{pos1: 0},
	{ScrollTo: 0},
	{camera: 0},
	{arrowCameraRight: 0},
	{arrowCameraLeft: 0},
	{Rotate: 0},
	{rotate_effect: 0},
	{title1: 0},
	{ch3: 0},
	{ch4: 0},
	{ch5: 0},
	{ch6: 0},
	{ch_blank: 0},
	{GameMonetizeSDK: 0},
	{Exit: 0},
	{Melody: 0},
	{color: 0},
	{chosenImage: 0},
	{camPos: 0}
];

self.InstanceType = {
	BtnPlay: class extends self.ISpriteInstance {},
	PaintingNotebook: class extends self.ISpriteInstance {},
	Images: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	WhiteEdge: class extends self.ISpriteInstance {},
	Brush: class extends self.ISpriteInstance {},
	BrushColor: class extends self.ISpriteInstance {},
	BrushSize: class extends self.ISpriteInstance {},
	BtnCamera: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	title0: class extends self.ISpriteInstance {},
	Sound: class extends self.IInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BrushMark: class extends self.ISpriteInstance {},
	TableExit: class extends self.ISpriteInstance {},
	BtnPrintExit: class extends self.ISpriteInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	Eraser: class extends self.ISpriteInstance {},
	BtnNextImages: class extends self.ISpriteInstance {},
	OpacityExit: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	TableUI: class extends self.ISpriteInstance {},
	BrushSizeAux: class extends self.ISpriteInstance {},
	NKGurl: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	ch1: class extends self.ISpriteInstance {},
	FireSparkParticlesMenu: class extends self.IParticlesInstance {},
	sky: class extends self.ISpriteInstance {},
	ch2: class extends self.ISpriteInstance {},
	btn_more_main: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	arrowCameraRight: class extends self.ISpriteInstance {},
	arrowCameraLeft: class extends self.ISpriteInstance {},
	rotate_effect: class extends self.ISpriteInstance {},
	title1: class extends self.ISpriteInstance {},
	ch3: class extends self.ISpriteInstance {},
	ch4: class extends self.ISpriteInstance {},
	ch5: class extends self.ISpriteInstance {},
	ch6: class extends self.ISpriteInstance {},
	ch_blank: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Exit: class extends self.ISpriteInstance {}
}