const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerAngle,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.RestoreObjectTimescale,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{arrow: 0},
	{Tween: 0},
	{blueRectangle: 0},
	{Sine: 0},
	{BlueRectangleEffect: 0},
	{blueRectangleParticle: 0},
	{CircleParticles: 0},
	{completeBoard: 0},
	{CrossParticles: 0},
	{damageEffect: 0},
	{damageEffect2: 0},
	{effectYellow: 0},
	{fade: 0},
	{fadeWhite: 0},
	{Solid: 0},
	{greenRectangle: 0},
	{homeButton: 0},
	{levelButton: 0},
	{line: 0},
	{maskGUI: 0},
	{menuButton: 0},
	{nextButton: 0},
	{overBoard: 0},
	{collisionblue: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{player: 0},
	{PlayerDestroyParticles: 0},
	{RectangleActive: 0},
	{RectangleParticles: 0},
	{restartButton: 0},
	{restartButtonOver: 0},
	{triggerMenu: 0},
	{WayParticles: 0},
	{whiteRectangle: 0},
	{yellowRectangle: 0},
	{level: 0},
	{LevelPlace: 0},
	{LevelsLogo: 0},
	{markNewBlue: 0},
	{markNewYellow: 0},
	{returnbutton: 0},
	{Background: 0},
	{logo: 0},
	{play: 0},
	{LevelNumber: 0},
	{textCompleted: 0},
	{textLevel: 0},
	{textTutorial: 0},
	{textTutorial2: 0},
	{textUnlocked: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{GameMonetizeSDK: 0},
	{Pin: 0},
	{GUIButtons: 0},
	{AllPlatforms: 0},
	{Boards: 0},
	{CompletedLevels: 0},
	{Win: 0},
	{LEVELS: 0},
	{Lose: 0},
	{AngleParticle: 0},
	{LayerRotated: 0}
];

self.InstanceType = {
	arrow: class extends self.ISpriteInstance {},
	blueRectangle: class extends self.ISpriteInstance {},
	BlueRectangleEffect: class extends self.ISpriteInstance {},
	blueRectangleParticle: class extends self.IParticlesInstance {},
	CircleParticles: class extends self.IParticlesInstance {},
	completeBoard: class extends self.ISpriteInstance {},
	CrossParticles: class extends self.IParticlesInstance {},
	damageEffect: class extends self.ISpriteInstance {},
	damageEffect2: class extends self.ISpriteInstance {},
	effectYellow: class extends self.ISpriteInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	fadeWhite: class extends self.ITiledBackgroundInstance {},
	greenRectangle: class extends self.ISpriteInstance {},
	homeButton: class extends self.ISpriteInstance {},
	levelButton: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	maskGUI: class extends self.ISpriteInstance {},
	menuButton: class extends self.ISpriteInstance {},
	nextButton: class extends self.ISpriteInstance {},
	overBoard: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	PlayerDestroyParticles: class extends self.IParticlesInstance {},
	RectangleActive: class extends self.ISpriteInstance {},
	RectangleParticles: class extends self.IParticlesInstance {},
	restartButton: class extends self.ISpriteInstance {},
	restartButtonOver: class extends self.ISpriteInstance {},
	triggerMenu: class extends self.ISpriteInstance {},
	WayParticles: class extends self.IParticlesInstance {},
	whiteRectangle: class extends self.ISpriteInstance {},
	yellowRectangle: class extends self.ISpriteInstance {},
	LevelPlace: class extends self.ISpriteInstance {},
	LevelsLogo: class extends self.ISpriteInstance {},
	markNewBlue: class extends self.ISpriteInstance {},
	markNewYellow: class extends self.ISpriteInstance {},
	returnbutton: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	LevelNumber: class extends self.ISpriteFontInstance {},
	textCompleted: class extends self.ISpriteFontInstance {},
	textLevel: class extends self.ISpriteFontInstance {},
	textTutorial: class extends self.ISpriteFontInstance {},
	textTutorial2: class extends self.ISpriteFontInstance {},
	textUnlocked: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	GUIButtons: class extends self.ISpriteInstance {},
	AllPlatforms: class extends self.ISpriteInstance {},
	Boards: class extends self.ISpriteInstance {}
}