const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.ScriptsInEvents.Global_Event111_Act1,
		C3.ScriptsInEvents.Global_Event113_Act1,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.ScriptsInEvents["Onstart-E_Event4_Act1"]
	];
};
self.C3_JsPropNameTable = [
	{ScoreCount: 0},
	{Timmesshows: 0},
	{LevCount: 0},
	{L1bgs: 0},
	{timeshow: 0},
	{Tween: 0},
	{Adsbtn: 0},
	{reload: 0},
	{levelshowsbtn: 0},
	{collecting: 0},
	{Wrongtap: 0},
	{minusval: 0},
	{sound: 0},
	{home2: 0},
	{X: 0},
	{highlight: 0},
	{inblack: 0},
	{outblack: 0},
	{complete_panel: 0},
	{home_btn: 0},
	{mg: 0},
	{nxt: 0},
	{winBack: 0},
	{failPanel: 0},
	{replay: 0},
	{menu: 0},
	{moregames: 0},
	{Sine: 0},
	{play: 0},
	{settings: 0},
	{hidden: 0},
	{backPad: 0},
	{PatricksDay: 0},
	{Leafleft: 0},
	{Flower: 0},
	{Shadow: 0},
	{Pump1: 0},
	{Sine2: 0},
	{TitlePumpkin: 0},
	{Levno: 0},
	{Levelselect: 0},
	{unlok: 0},
	{LevelLock: 0},
	{LevelSelectPanel: 0},
	{back: 0},
	{obj: 0},
	{Touch: 0},
	{obj2: 0},
	{hint: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{handindications: 0},
	{Particles: 0},
	{Bags: 0},
	{BGS: 0},
	{play_btn: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{tap: 0},
	{btns: 0},
	{fail: 0},
	{score: 0},
	{start: 0},
	{Times: 0},
	{c_lev: 0},
	{complete: 0},
	{intract: 0},
	{touch: 0},
	{Ad_mute: 0},
	{wait: 0},
	{Ad_time: 0},
	{u_lev: 0},
	{Catagery: 0},
	{Click: 0},
	{Object_name: 0},
	{Time_time: 0},
	{TouchBack: 0}
];

self.InstanceType = {
	ScoreCount: class extends self.ISpriteFontInstance {},
	Timmesshows: class extends self.ISpriteFontInstance {},
	LevCount: class extends self.ISpriteFontInstance {},
	L1bgs: class extends self.ISpriteInstance {},
	timeshow: class extends self.ISpriteInstance {},
	Adsbtn: class extends self.ISpriteInstance {},
	reload: class extends self.ISpriteInstance {},
	levelshowsbtn: class extends self.ISpriteInstance {},
	collecting: class extends self.ISpriteInstance {},
	Wrongtap: class extends self.ISpriteInstance {},
	minusval: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	home2: class extends self.ISpriteInstance {},
	X: class extends self.ISpriteInstance {},
	highlight: class extends self.ISpriteInstance {},
	inblack: class extends self.ISpriteInstance {},
	outblack: class extends self.ISpriteInstance {},
	complete_panel: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	mg: class extends self.ISpriteInstance {},
	nxt: class extends self.ISpriteInstance {},
	winBack: class extends self.ISpriteInstance {},
	failPanel: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	hidden: class extends self.ISpriteInstance {},
	backPad: class extends self.ISpriteInstance {},
	PatricksDay: class extends self.ISpriteInstance {},
	Leafleft: class extends self.ISpriteInstance {},
	Flower: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	TitlePumpkin: class extends self.ISpriteInstance {},
	Levelselect: class extends self.ISpriteInstance {},
	LevelLock: class extends self.ISpriteInstance {},
	LevelSelectPanel: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	obj: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	obj2: class extends self.ISpriteInstance {},
	hint: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	handindications: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Bags: class extends self.ISpriteInstance {},
	BGS: class extends self.ISpriteInstance {},
	play_btn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	tap: class extends self.ISpriteInstance {},
	btns: class extends self.ISpriteInstance {}
}