const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Timer,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Function.Exps.Param,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.System.Exps.find,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_installgamebutton: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_separater: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{adl_update_button: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_white_back: 0},
	{Array: 0},
	{ArrayPercent: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{LocalStorage: 0},
	{Title: 0},
	{Touch: 0},
	{Video: 0},
	{Black: 0},
	{MyY: 0},
	{HasItem: 0},
	{Block: 0},
	{Tween: 0},
	{Cam: 0},
	{Checker: 0},
	{parent: 0},
	{Item: 0},
	{changeColor: 0},
	{Player: 0},
	{Wrap: 0},
	{Background: 0},
	{StartBlack: 0},
	{TiledBackground: 0},
	{BlackC: 0},
	{InfoBox: 0},
	{Sine: 0},
	{seaHorse: 0},
	{TapToRestart: 0},
	{Pin: 0},
	{BtnClose: 0},
	{BtnHome: 0},
	{BtnInfo: 0},
	{BtnMusic: 0},
	{BtnPlay: 0},
	{BtnSound: 0},
	{Back_Variable: 0},
	{back_btnasset: 0},
	{htp: 0},
	{menu_btnasset: 0},
	{Next_Variable: 0},
	{next_btnasset: 0},
	{tutorial: 0},
	{txtBestScore: 0},
	{txtLabel: 0},
	{txtScore: 0},
	{txtScoreGame: 0},
	{txtStartText: 0},
	{Timer: 0},
	{txtTimer: 0},
	{GMText: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{GameMonetizeSDK: 0},
	{FBlock: 0},
	{FItem: 0},
	{ColorsList: 0},
	{StartBlockColor: 0},
	{TimeSec: 0},
	{Score: 0},
	{BestScore: 0},
	{GameOverTimer: 0},
	{rnd: 0},
	{Info: 0},
	{Music: 0},
	{Sound: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	ArrayPercent: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Title: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	Block: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {},
	Checker: class extends self.ISpriteInstance {},
	Item: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	StartBlack: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	BlackC: class extends self.ITiledBackgroundInstance {},
	InfoBox: class extends self.ISpriteInstance {},
	seaHorse: class extends self.ISpriteInstance {},
	TapToRestart: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	back_btnasset: class extends self.ISpriteInstance {},
	htp: class extends self.ISpriteInstance {},
	menu_btnasset: class extends self.ISpriteInstance {},
	next_btnasset: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	txtBestScore: class extends self.ISpriteFontInstance {},
	txtLabel: class extends self.ISpriteFontInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	txtScoreGame: class extends self.ISpriteFontInstance {},
	txtStartText: class extends self.ISpriteFontInstance {},
	txtTimer: class extends self.ISpriteFontInstance {},
	GMText: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	FBlock: class extends self.ISpriteInstance {},
	FItem: class extends self.ISpriteInstance {}
}