const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.bound,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.IsSuspended,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width
	];
};
self.C3_JsPropNameTable = [
	{DeckValues: 0},
	{DeckSuits: 0},
	{UnshuffledFrames: 0},
	{StockArray: 0},
	{ValidFoundationMoves: 0},
	{ValidStackMoves: 0},
	{Browser: 0},
	{Touch: 0},
	{Mouse: 0},
	{LocalStorage: 0},
	{MenuButton: 0},
	{Name: 0},
	{checkBtnText: 0},
	{Checkbox: 0},
	{Instructions: 0},
	{Suit: 0},
	{TopCardValue: 0},
	{Foundation: 0},
	{Index: 0},
	{TopCardSuit: 0},
	{IsEmpty: 0},
	{CardsInStack: 0},
	{Stack: 0},
	{Discard: 0},
	{Value: 0},
	{DragDrop: 0},
	{Tween: 0},
	{BoundToLayout: 0},
	{Card: 0},
	{StackIndicator: 0},
	{Shadow: 0},
	{pressed: 0},
	{settingsBtn: 0},
	{creditsBtn: 0},
	{helpBtn: 0},
	{resumeBtn: 0},
	{playBtn: 0},
	{cursor: 0},
	{Anchor: 0},
	{TitleNapoleonCredits: 0},
	{Pin: 0},
	{creditsFaces: 0},
	{backBtn: 0},
	{Next: 0},
	{howToPlay: 0},
	{HelpImageRight: 0},
	{tagline: 0},
	{tagLineShadow: 0},
	{TiledBackground: 0},
	{TiledBackgroundLines: 0},
	{Audio: 0},
	{checkBtnTextShadow: 0},
	{favouriteDeckText: 0},
	{NapoleonTitleMainMenu: 0},
	{NapoleonTitleSettings: 0},
	{backBtnSettings: 0},
	{CardTypes: 0},
	{type1Text: 0},
	{type2Text: 0},
	{type3Text: 0},
	{NapoleonSplashLogo: 0},
	{developedByCatabit: 0},
	{LoadingBarEdge: 0},
	{loadingBar: 0},
	{Sprite: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{GameMonetizeSDK: 0},
	{HelpSettingsCreditsBtn: 0},
	{ResumePlayBtn: 0},
	{DraggedFromUID: 0},
	{DraggedFromType: 0},
	{Deck: 0},
	{DeckScale: 0},
	{DEFAULT_DECK: 0},
	{DEFAULT_DECK_SCALE: 0},
	{HasBegunDealing: 0},
	{IsSavingBeforeTransitionToMenu: 0},
	{IsSkippingAnimations: 0},
	{IsDealing: 0},
	{fattoreDiScala: 0},
	{PickIndex: 0},
	{StackToMoveTo: 0},
	{CardIndex: 0},
	{CardSuit: 0},
	{CardValue: 0},
	{CardUID: 0},
	{DiscardedCards: 0},
	{CompletedFoundations: 0},
	{ExceptionUID: 0},
	{CardFrame: 0},
	{InstructionsScreen: 0},
	{backgroundNumber: 0}
];

self.InstanceType = {
	DeckValues: class extends self.IArrayInstance {},
	DeckSuits: class extends self.IArrayInstance {},
	UnshuffledFrames: class extends self.IArrayInstance {},
	StockArray: class extends self.IArrayInstance {},
	ValidFoundationMoves: class extends self.IArrayInstance {},
	ValidStackMoves: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	checkBtnText: class extends self.ITextInstance {},
	Checkbox: class extends self.ISpriteInstance {},
	Instructions: class extends self.ISpriteInstance {},
	Foundation: class extends self.ISpriteInstance {},
	Stack: class extends self.ISpriteInstance {},
	Discard: class extends self.ISpriteInstance {},
	Card: class extends self.ISpriteInstance {},
	StackIndicator: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	settingsBtn: class extends self.ISpriteInstance {},
	creditsBtn: class extends self.ISpriteInstance {},
	helpBtn: class extends self.ISpriteInstance {},
	resumeBtn: class extends self.ISpriteInstance {},
	playBtn: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	TitleNapoleonCredits: class extends self.ISpriteInstance {},
	creditsFaces: class extends self.ISpriteInstance {},
	backBtn: class extends self.ISpriteInstance {},
	Next: class extends self.ISpriteInstance {},
	howToPlay: class extends self.ISpriteInstance {},
	HelpImageRight: class extends self.ISpriteInstance {},
	tagline: class extends self.ITextInstance {},
	tagLineShadow: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackgroundLines: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	checkBtnTextShadow: class extends self.ITextInstance {},
	favouriteDeckText: class extends self.ITextInstance {},
	NapoleonTitleMainMenu: class extends self.ISpriteInstance {},
	NapoleonTitleSettings: class extends self.ISpriteInstance {},
	backBtnSettings: class extends self.ISpriteInstance {},
	CardTypes: class extends self.ISpriteInstance {},
	type1Text: class extends self.ITextInstance {},
	type2Text: class extends self.ITextInstance {},
	type3Text: class extends self.ITextInstance {},
	NapoleonSplashLogo: class extends self.ISpriteInstance {},
	developedByCatabit: class extends self.ISpriteInstance {},
	LoadingBarEdge: class extends self.ISpriteInstance {},
	loadingBar: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	HelpSettingsCreditsBtn: class extends self.ISpriteInstance {},
	ResumePlayBtn: class extends self.ISpriteInstance {}
}