const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.GM_SDK,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{cur_x: 0},
	{cur_y: 0},
	{id: 0},
	{touching: 0},
	{active: 0},
	{shuffle: 0},
	{destroy: 0},
	{card_1: 0},
	{array_field: 0},
	{AJAX: 0},
	{array_random: 0},
	{Touch: 0},
	{Keyboard: 0},
	{array_id: 0},
	{array_storage_path: 0},
	{Browser: 0},
	{array_path: 0},
	{point: 0},
	{checked: 0},
	{path: 0},
	{Tween: 0},
	{tile: 0},
	{card_2: 0},
	{card_3: 0},
	{card_4: 0},
	{card_5: 0},
	{card_6: 0},
	{card_7: 0},
	{card_8: 0},
	{card_9: 0},
	{card_10: 0},
	{card_11: 0},
	{card_12: 0},
	{card_13: 0},
	{card_14: 0},
	{card_15: 0},
	{line: 0},
	{line_point: 0},
	{array_hint: 0},
	{array_line: 0},
	{options: 0},
	{btn_reshuffle: 0},
	{btn_show: 0},
	{Sprite: 0},
	{card_16: 0},
	{card_17: 0},
	{ToolTip: 0},
	{Pin: 0},
	{Snow: 0},
	{ButtonReset: 0},
	{pozadinazareset: 0},
	{audioOn: 0},
	{BSound: 0},
	{pozadinazazvuk: 0},
	{pozadinazamenu: 0},
	{menu: 0},
	{Sprite2: 0},
	{addtimereklama: 0},
	{shufflebtn: 0},
	{Anchor: 0},
	{StarsFont3: 0},
	{Sprite3: 0},
	{showmatch: 0},
	{Sprite4: 0},
	{Sprite16: 0},
	{TextIndex: 0},
	{TextFont: 0},
	{igraj: 0},
	{MOREICO: 0},
	{PLAYTEXT: 0},
	{pokazatelj: 0},
	{Sprite5: 0},
	{Sprite30: 0},
	{Sine: 0},
	{Sprite6: 0},
	{ParticlesZAKRAJ: 0},
	{pozadinamuzika: 0},
	{WIN: 0},
	{ButtonGameKraj: 0},
	{nextlevel: 0},
	{BackgroundSprite: 0},
	{Sprite7: 0},
	{card_18: 0},
	{card_19: 0},
	{card_20: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{howto: 0},
	{Sprite13: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{SpriteFont123: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{LevelsText: 0},
	{FireworkParticles2: 0},
	{x: 0},
	{pozadinazazvuk2: 0},
	{Sprite15: 0},
	{Audio: 0},
	{card_21: 0},
	{card_22: 0},
	{card_23: 0},
	{card_24: 0},
	{card_25: 0},
	{card_26: 0},
	{card_27: 0},
	{POZADINAZAREWARDED: 0},
	{Sprite18: 0},
	{howto2: 0},
	{igraj2: 0},
	{card_28: 0},
	{card_29: 0},
	{card_30: 0},
	{HINT: 0},
	{Sprite14: 0},
	{Sprite19: 0},
	{nextlevel2: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{pozadinamuzika2: 0},
	{ButtonGameKraj2: 0},
	{kockazarewarded: 0},
	{StarsFont: 0},
	{ScoreText: 0},
	{zidzahow: 0},
	{ShopCharacter1: 0},
	{ShopCharacter2: 0},
	{ShopCharacter3: 0},
	{ShopCharacter4: 0},
	{ShopCharacter5: 0},
	{ShopCharacter6: 0},
	{ShopCharacter7: 0},
	{ShopCharacter8: 0},
	{ShopCharacter9: 0},
	{ShopCharacter10: 0},
	{ShopCharacter11: 0},
	{ShopCharacter12: 0},
	{ShopCharacter13: 0},
	{ShopCharacter14: 0},
	{ShopCharacter15: 0},
	{ShopCharacter16: 0},
	{ShopCharacter17: 0},
	{ShopCharacter18: 0},
	{ShopCharacter19: 0},
	{ShopCharacter20: 0},
	{ShopSelector: 0},
	{Lockdrugilik: 0},
	{Lockdrugilik2: 0},
	{Lockdrugilik3: 0},
	{Lockdrugilik4: 0},
	{Lockdrugilik5: 0},
	{Lockdrugilik6: 0},
	{Lockdrugilik7: 0},
	{Lockdrugilik8: 0},
	{Lockdrugilik9: 0},
	{StarsFont2: 0},
	{Particles4: 0},
	{shopdugme: 0},
	{pozadinazashop: 0},
	{LiteTweenH: 0},
	{LiteTweenV: 0},
	{LiteTween: 0},
	{PlayerSkins: 0},
	{shufflebtn2: 0},
	{StarsFont4: 0},
	{pozadinazaaddgifts: 0},
	{Sprite22: 0},
	{Solid: 0},
	{sendvic: 0},
	{CoinIcon: 0},
	{CoinIcon2: 0},
	{Money: 0},
	{dugmerewarded: 0},
	{norewarded: 0},
	{btn_show2: 0},
	{showmatch2: 0},
	{Fade: 0},
	{MessageBox: 0},
	{Sprite17: 0},
	{Sprite23: 0},
	{igraj3: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{a: 0},
	{Wheel: 0},
	{Text: 0},
	{zavrti: 0},
	{playzawheels: 0},
	{zavrtisareklamama: 0},
	{addmetakreklama: 0},
	{zavrti3: 0},
	{ruke: 0},
	{metci: 0},
	{krug: 0},
	{aha: 0},
	{zavrti2: 0},
	{zavrti4: 0},
	{metci2: 0},
	{wheels: 0},
	{confeti: 0},
	{GameMonetizeSDK: 0},
	{moregames: 0},
	{cards_fam: 0},
	{Unlock20: 0},
	{Unlock19: 0},
	{Unlock18: 0},
	{Unlock17: 0},
	{Unlock16: 0},
	{Unlock15: 0},
	{Unlock14: 0},
	{Unlock13: 0},
	{Unlock12: 0},
	{Unlock11: 0},
	{Unlock10: 0},
	{Unlock9: 0},
	{Unlock8: 0},
	{Unlock7: 0},
	{Unlock6: 0},
	{Unlock5: 0},
	{Unlock4: 0},
	{Unlock3: 0},
	{Unlock2: 0},
	{Unlock1: 0},
	{PlayerScore: 0},
	{Score: 0},
	{STARSVALUE: 0},
	{LEVEL_VALUE: 0},
	{character: 0},
	{unlocks: 0},
	{stars: 0},
	{sound: 0},
	{SoundEf: 0},
	{LastLevel: 0},
	{LevelComplete: 0},
	{LAST_LEVEL: 0},
	{last_id: 0},
	{state: 0},
	{path_count: 0},
	{cur_value: 0},
	{rand_i: 0},
	{w: 0},
	{h: 0},
	{margin: 0},
	{i: 0},
	{start_x: 0},
	{start_y: 0},
	{end_x: 0},
	{end_y: 0},
	{delta_x: 0},
	{delta_y: 0},
	{show: 0},
	{brake: 0},
	{x1: 0},
	{x2: 0},
	{y1: 0},
	{y2: 0},
	{ex: 0},
	{ey: 0},
	{ang: 0},
	{sectorCount: 0},
	{prizes: 0},
	{Stars2: 0},
	{Metci: 0},
	{winningSector: 0}
];

self.InstanceType = {
	card_1: class extends self.ISpriteInstance {},
	array_field: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	array_random: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	array_id: class extends self.IArrayInstance {},
	array_storage_path: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	array_path: class extends self.IArrayInstance {},
	point: class extends self.ISpriteInstance {},
	tile: class extends self.ISpriteInstance {},
	card_2: class extends self.ISpriteInstance {},
	card_3: class extends self.ISpriteInstance {},
	card_4: class extends self.ISpriteInstance {},
	card_5: class extends self.ISpriteInstance {},
	card_6: class extends self.ISpriteInstance {},
	card_7: class extends self.ISpriteInstance {},
	card_8: class extends self.ISpriteInstance {},
	card_9: class extends self.ISpriteInstance {},
	card_10: class extends self.ISpriteInstance {},
	card_11: class extends self.ISpriteInstance {},
	card_12: class extends self.ISpriteInstance {},
	card_13: class extends self.ISpriteInstance {},
	card_14: class extends self.ISpriteInstance {},
	card_15: class extends self.ISpriteInstance {},
	line: class extends self.ITiledBackgroundInstance {},
	line_point: class extends self.ISpriteInstance {},
	array_hint: class extends self.IArrayInstance {},
	array_line: class extends self.IArrayInstance {},
	options: class extends self.ISpriteInstance {},
	btn_reshuffle: class extends self.IButtonInstance {},
	btn_show: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	card_16: class extends self.ISpriteInstance {},
	card_17: class extends self.ISpriteInstance {},
	Snow: class extends self.IParticlesInstance {},
	ButtonReset: class extends self.ISpriteInstance {},
	pozadinazareset: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	pozadinazazvuk: class extends self.ISpriteInstance {},
	pozadinazamenu: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	addtimereklama: class extends self.ISpriteInstance {},
	shufflebtn: class extends self.ISpriteInstance {},
	StarsFont3: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	showmatch: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	igraj: class extends self.ISpriteInstance {},
	MOREICO: class extends self.ISpriteInstance {},
	PLAYTEXT: class extends self.ISpriteInstance {},
	pokazatelj: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ParticlesZAKRAJ: class extends self.IParticlesInstance {},
	pozadinamuzika: class extends self.ISpriteInstance {},
	WIN: class extends self.ISpriteInstance {},
	ButtonGameKraj: class extends self.ISpriteInstance {},
	nextlevel: class extends self.ISpriteInstance {},
	BackgroundSprite: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	card_18: class extends self.ISpriteInstance {},
	card_19: class extends self.ISpriteInstance {},
	card_20: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	howto: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	FireworkParticles2: class extends self.IParticlesInstance {},
	x: class extends self.ISpriteInstance {},
	pozadinazazvuk2: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	card_21: class extends self.ISpriteInstance {},
	card_22: class extends self.ISpriteInstance {},
	card_23: class extends self.ISpriteInstance {},
	card_24: class extends self.ISpriteInstance {},
	card_25: class extends self.ISpriteInstance {},
	card_26: class extends self.ISpriteInstance {},
	card_27: class extends self.ISpriteInstance {},
	POZADINAZAREWARDED: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	howto2: class extends self.ISpriteInstance {},
	igraj2: class extends self.ISpriteInstance {},
	card_28: class extends self.ISpriteInstance {},
	card_29: class extends self.ISpriteInstance {},
	card_30: class extends self.ISpriteInstance {},
	HINT: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	nextlevel2: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	pozadinamuzika2: class extends self.ISpriteInstance {},
	ButtonGameKraj2: class extends self.ISpriteInstance {},
	kockazarewarded: class extends self.ISpriteInstance {},
	StarsFont: class extends self.ISpriteFontInstance {},
	ScoreText: class extends self.ITextInstance {},
	zidzahow: class extends self.ISpriteInstance {},
	ShopCharacter1: class extends self.ISpriteInstance {},
	ShopCharacter2: class extends self.ISpriteInstance {},
	ShopCharacter3: class extends self.ISpriteInstance {},
	ShopCharacter4: class extends self.ISpriteInstance {},
	ShopCharacter5: class extends self.ISpriteInstance {},
	ShopCharacter6: class extends self.ISpriteInstance {},
	ShopCharacter7: class extends self.ISpriteInstance {},
	ShopCharacter8: class extends self.ISpriteInstance {},
	ShopCharacter9: class extends self.ISpriteInstance {},
	ShopCharacter10: class extends self.ISpriteInstance {},
	ShopCharacter11: class extends self.ISpriteInstance {},
	ShopCharacter12: class extends self.ISpriteInstance {},
	ShopCharacter13: class extends self.ISpriteInstance {},
	ShopCharacter14: class extends self.ISpriteInstance {},
	ShopCharacter15: class extends self.ISpriteInstance {},
	ShopCharacter16: class extends self.ISpriteInstance {},
	ShopCharacter17: class extends self.ISpriteInstance {},
	ShopCharacter18: class extends self.ISpriteInstance {},
	ShopCharacter19: class extends self.ISpriteInstance {},
	ShopCharacter20: class extends self.ISpriteInstance {},
	ShopSelector: class extends self.ISpriteInstance {},
	Lockdrugilik: class extends self.ISpriteInstance {},
	Lockdrugilik2: class extends self.ISpriteInstance {},
	Lockdrugilik3: class extends self.ISpriteInstance {},
	Lockdrugilik4: class extends self.ISpriteInstance {},
	Lockdrugilik5: class extends self.ISpriteInstance {},
	Lockdrugilik6: class extends self.ISpriteInstance {},
	Lockdrugilik7: class extends self.ISpriteInstance {},
	Lockdrugilik8: class extends self.ISpriteInstance {},
	Lockdrugilik9: class extends self.ISpriteInstance {},
	StarsFont2: class extends self.ISpriteFontInstance {},
	Particles4: class extends self.IParticlesInstance {},
	shopdugme: class extends self.ISpriteInstance {},
	pozadinazashop: class extends self.ISpriteInstance {},
	PlayerSkins: class extends self.ISpriteInstance {},
	shufflebtn2: class extends self.ISpriteInstance {},
	StarsFont4: class extends self.ISpriteFontInstance {},
	pozadinazaaddgifts: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	sendvic: class extends self.ISpriteInstance {},
	CoinIcon: class extends self.ISpriteInstance {},
	CoinIcon2: class extends self.ISpriteInstance {},
	Money: class extends self.IParticlesInstance {},
	dugmerewarded: class extends self.ISpriteInstance {},
	norewarded: class extends self.ISpriteInstance {},
	btn_show2: class extends self.IButtonInstance {},
	showmatch2: class extends self.ISpriteInstance {},
	MessageBox: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	igraj3: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Wheel: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	zavrti: class extends self.ISpriteInstance {},
	playzawheels: class extends self.ISpriteInstance {},
	zavrtisareklamama: class extends self.ISpriteInstance {},
	addmetakreklama: class extends self.ISpriteInstance {},
	zavrti3: class extends self.ISpriteInstance {},
	ruke: class extends self.ISpriteFontInstance {},
	metci: class extends self.ITextInstance {},
	krug: class extends self.ISpriteInstance {},
	Pin: class extends self.ISpriteInstance {},
	aha: class extends self.ITextInstance {},
	zavrti2: class extends self.ISpriteInstance {},
	zavrti4: class extends self.ISpriteInstance {},
	metci2: class extends self.ITextInstance {},
	wheels: class extends self.ISpriteInstance {},
	confeti: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	moregames: class extends self.ISpriteInstance {},
	cards_fam: class extends self.ISpriteInstance {}
}