const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Flash,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Text.Acts.SetHeight,
		C3.Plugins.Text.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Acts.Delete,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{intro_: 0},
	{Sine: 0},
	{txt_taptocontinue: 0},
	{Touch: 0},
	{debug: 0},
	{Audio: 0},
	{fade: 0},
	{Anchor: 0},
	{btn_main: 0},
	{btn_sound: 0},
	{bgPaused: 0},
	{b_play: 0},
	{txt_ver: 0},
	{changed: 0},
	{memPos: 0},
	{Tween: 0},
	{slot: 0},
	{memX: 0},
	{memY: 0},
	{slotThrow: 0},
	{newColor: 0},
	{compare: 0},
	{setColor: 0},
	{a_colorsInLevel: 0},
	{Timer: 0},
	{txt_status: 0},
	{completedBG: 0},
	{pause: 0},
	{btn_restart: 0},
	{title: 0},
	{txt_levelSelect: 0},
	{btn_levels: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{bgGame: 0},
	{fontSizeDefault: 0},
	{txt_congrats: 0},
	{alch: 0},
	{balloon: 0},
	{txt_msg: 0},
	{steps: 0},
	{btn_intro: 0},
	{Flash: 0},
	{btn_end: 0},
	{handAlch: 0},
	{bgMain: 0},
	{mainBoard: 0},
	{btn_music: 0},
	{txt_credits: 0},
	{GameMonetizeSDK: 0},
	{load_ok: 0},
	{storageName: 0},
	{timeAnimation: 0},
	{currentLevel: 0},
	{totalLevels: 0},
	{firstTime: 0},
	{counter: 0},
	{p_colorClicked: 0},
	{color: 0},
	{count: 0},
	{p_msgShow: 0},
	{p_intro: 0},
	{Sound: 0},
	{Music: 0},
	{fadeTime: 0},
	{type: 0},
	{control: 0}
];

self.InstanceType = {
	intro_: class extends self.ISpriteInstance {},
	txt_taptocontinue: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	debug: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	btn_main: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	bgPaused: class extends self.ITiledBackgroundInstance {},
	b_play: class extends self.ISpriteInstance {},
	txt_ver: class extends self.ITextInstance {},
	slot: class extends self.ISpriteInstance {},
	slotThrow: class extends self.ISpriteInstance {},
	setColor: class extends self.ISpriteInstance {},
	a_colorsInLevel: class extends self.IArrayInstance {},
	txt_status: class extends self.ITextInstance {},
	completedBG: class extends self.ITiledBackgroundInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	txt_levelSelect: class extends self.ITextInstance {},
	btn_levels: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	bgGame: class extends self.ITiledBackgroundInstance {},
	txt_congrats: class extends self.ITextInstance {},
	alch: class extends self.ISpriteInstance {},
	balloon: class extends self.ISpriteInstance {},
	txt_msg: class extends self.ITextInstance {},
	btn_intro: class extends self.ISpriteInstance {},
	btn_end: class extends self.ISpriteInstance {},
	handAlch: class extends self.ISpriteInstance {},
	bgMain: class extends self.ISpriteInstance {},
	mainBoard: class extends self.ITiledBackgroundInstance {},
	btn_music: class extends self.ISpriteInstance {},
	txt_credits: class extends self.ITextInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}