const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.SVGPicture,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Cnds.CompareX,
		C3.Plugins.SVGPicture.Exps.X,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.SVGPicture.Exps.Y,
		C3.Plugins.SVGPicture.Acts.AddChild,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.SVGPicture.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.SVGPicture.Cnds.CompareX,
		C3.Plugins.SVGPicture.Cnds.CompareY,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.SVGPicture.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.SVGPicture.Exps.Count,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Acts.SetVAlign,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.SVGPicture.Acts.SetImage,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{posX: 0},
	{posY: 0},
	{Tween: 0},
	{PuzzlePiece: 0},
	{Touch: 0},
	{Null: 0},
	{Sine: 0},
	{GameManager: 0},
	{Audio: 0},
	{Block_text: 0},
	{Black: 0},
	{Var: 0},
	{SpriteFont: 0},
	{Start: 0},
	{BG1: 0},
	{BG2: 0},
	{Array: 0},
	{Board: 0},
	{Pause: 0},
	{Next: 0},
	{Restart: 0},
	{LocalStorage: 0},
	{CLOSE: 0},
	{Levels: 0},
	{Asset2: 0},
	{Board2: 0},
	{Sprite: 0},
	{Pin: 0},
	{obj_pinpoint: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Bullet: 0},
	{"8Direction": 0},
	{obj_camera: 0},
	{Board3: 0},
	{Board_text: 0},
	{Back: 0},
	{Title: 0},
	{mask: 0},
	{GameMask: 0},
	{TiledBackground: 0},
	{www: 0},
	{g8: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{ads: 0},
	{more: 0},
	{BGs: 0},
	{StartPlay: 0},
	{Count: 0},
	{Count2: 0},
	{Win: 0},
	{Timer: 0},
	{piecePositions: 0},
	{Score: 0},
	{inter: 0}
];

self.InstanceType = {
	PuzzlePiece: class extends self.ISVGPictureInstance {},
	Touch: class extends self.IInstance {},
	Null: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Block_text: class extends self.ITextInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Start: class extends self.ISpriteInstance {},
	BG1: class extends self.ITiledBackgroundInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	Array: class extends self.IArrayInstance {},
	Board: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Next: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	CLOSE: class extends self.ISpriteInstance {},
	Levels: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Board2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	obj_pinpoint: class extends self.ISpriteInstance {},
	obj_camera: class extends self.ISpriteInstance {},
	Board3: class extends self.ISpriteInstance {},
	Board_text: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	mask: class extends self.ITiledBackgroundInstance {},
	GameMask: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	www: class extends self.ISpriteInstance {},
	g8: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	ads: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	BGs: class extends self.ITiledBackgroundInstance {}
}