var audioEnabled=!0,confirmAnswer=!1,answerWindow=!1,duralex=!1,puntiRisposta=0,glowPos=new me.Vector2d(0,0),glowType="none",divDidattica={},game={globals:{message:"",score:[],tabellone:[],playernumGroup:[],playernum:2,playerhumanGroup:[],playerhuman:1,nomeGiocatore:[],avatarGiocatore:[],posizioneGiocatore:[],statoGiocatore:[],caselleUsate:["",[],[],[],[]],currentPlayer:1,roundNumber:1,valoreDado:0,spostamenti:0,cpuDice:!1,movePlayer:0,animLuna:"idle",audio:!0,timer:!0,answerTime:91},onload:function(){if(me.video.init("screen",
1024,768,!0,"auto")){if("#debug"===document.location.hash)window.onReady(function(){me.plugin.register.defer(this,debugPanel,"debug")});if("#mute"===document.location.hash)window.onReady(function(){audioEnabled=!1});me.sys.interpolation=!0;me.sys.scalingInterpolation=!0;me.audio.init("mp3,ogg");me.loader.onload=this.loaded.bind(this);me.loader.preload(game.resources);me.state.change(me.state.LOADING)}else alert("Your browser does not support HTML5 canvas.")},loaded:function(){me.state.set(me.state.MENU,
new game.HomeScreen);me.state.set(me.state.USER+1,new game.InfoScreen);me.state.set(me.state.USER+3,new game.QuantiGiocatoriScreen);me.state.set(me.state.USER+4,new game.InputNomeScreen);me.state.set(me.state.USER+5,new game.finale);me.state.set(me.state.USER+6,new game.AlertPlayScreen);me.state.set(me.state.USER+7,new game.AlertQuitScreen);me.state.set(me.state.USER+8,new game.AlertInputScreen);me.state.set(me.state.PLAY,new game.PlayScreen);me.pool.register("but_gioca",game.but_gioca);me.pool.register("but_help",
game.but_help);me.pool.register("but_info",game.but_info);me.pool.register("but_gohome",game.but_gohome);me.pool.register("but_link",game.but_link);me.pool.register("but_pdf",game.but_pdf);me.pool.register("but_quit",game.but_quit);me.pool.register("but_play",game.but_play);me.pool.register("but_playernum",game.but_playernum);me.pool.register("but_playerhuman",game.but_playerhuman);me.pool.register("but_continue",game.but_continue);me.pool.register("but_avatar",game.but_avatar);me.pool.register("but_input",
game.but_input);me.pool.register("but_continua_si",game.but_continua_si);me.pool.register("but_continua_no",game.but_continua_no);me.pool.register("but_inserisci_ok",game.but_inserisci_ok);me.pool.register("Text",game.Text);me.pool.register("numero_giocatore",game.numero_giocatore);me.pool.register("controller",game.controllerEntity);me.pool.register("casella",game.casellaEntity);me.pool.register("message",game.messageEntity);me.pool.register("dado",game.dadoEntity);me.pool.register("showCurrentPlayer",
game.showCurrentPlayerEntity);me.pool.register("espressioniLuna",game.EspressioniLunaEntity);me.pool.register("animLuna",game.animLuna);me.pool.register("nomeVincitore",game.nomeVincitore);me.input.bindKey(me.input.KEY.SPACE,"dice",!0);me.input.bindKey(me.input.KEY.ENTER,"continue",!0);me.input.bindKey(me.input.KEY.NUM1,"1",!0);me.input.bindKey(me.input.KEY.NUM2,"2",!0);me.input.bindKey(me.input.KEY.NUM3,"3",!0);me.input.bindPointer(me.input.mouse.LEFT,me.input.KEY.SPACE);0<TIMER?(game.globals.timer=
!0,game.globals.answerTime=TIMER):game.globals.timer=!1;me.save.add({audio:!1,timer:!1,roundNumber:0,currentPlayer:0,playernum:0,playerhuman:0,valoreDado:0,nomeGiocatore:[],avatarGiocatore:[],posizioneGiocatore:[],statoGiocatore:[],movePlayer:0});me.state.change(me.state.MENU)},resources:[{name:"cg1",type:"image",src:"data/img/cg1.png"},{name:"cg2",type:"image",src:"data/img/cg2.png"},{name:"cg3",type:"image",src:"data/img/cg3.png"},{name:"cg4",type:"image",src:"data/img/cg4.png"},{name:"robot",type:"image",
src:"data/img/robot.png"},{name:"big_cg1",type:"image",src:"data/img/big_cg1.png"},{name:"big_cg2",type:"image",src:"data/img/big_cg2.png"},{name:"big_cg3",type:"image",src:"data/img/big_cg3.png"},{name:"big_cg4",type:"image",src:"data/img/big_cg4.png"},{name:"big_robot",type:"image",src:"data/img/big_robot.png"},{name:"dado",type:"image",src:"data/img/dice.png"},{name:"transparent",type:"image",src:"data/img/transparent.png"},{name:"home",type:"image",src:"data/img/home.png"},{name:"info",type:"image",
src:"data/img/info.png"},{name:"inputName",type:"image",src:"data/img/inputName.png"},{name:"howmanyplayers",type:"image",src:"data/img/howmanyplayers.png"},{name:"1up",type:"image",src:"data/img/1up.png"},{name:"1dw",type:"image",src:"data/img/1dw.png"},{name:"2up",type:"image",src:"data/img/2up.png"},{name:"2dw",type:"image",src:"data/img/2dw.png"},{name:"3up",type:"image",src:"data/img/3up.png"},{name:"3dw",type:"image",src:"data/img/3dw.png"},{name:"4up",type:"image",src:"data/img/4up.png"},{name:"4dw",
type:"image",src:"data/img/4dw.png"},{name:"victory",type:"image",src:"data/img/victory.png"},{name:"alert_resume",type:"image",src:"data/img/alert_resume.png"},{name:"alert_insert",type:"image",src:"data/img/alert_insert.png"},{name:"n1",type:"image",src:"data/img/1.png"},{name:"n2",type:"image",src:"data/img/2.png"},{name:"n3",type:"image",src:"data/img/3.png"},{name:"n4",type:"image",src:"data/img/4.png"},{name:"board",type:"image",src:"data/img/board.png"},{name:"bg_quiz_duralex",type:"image",
src:"data/img/bg_quiz.png"},{name:"quiz_button",type:"image",src:"data/img/quiz_button.png"},{name:"glow",type:"image",src:"data/img/glow.png"},{name:"glowStart",type:"image",src:"data/img/glowStart.png"},{name:"glowGoal",type:"image",src:"data/img/glowGoal.png"},{name:"duralex",type:"json",src:"data/json/questions.json"},{name:"home",type:"tmx",src:"data/screen/home.json"},{name:"info",type:"tmx",src:"data/screen/info.json"},{name:"inputNome",type:"tmx",src:"data/screen/inputName.json"},{name:"quantiGiocatori",
type:"tmx",src:"data/screen/howmanyplayers.json"},{name:"tabellone",type:"tmx",src:"data/screen/board.json"},{name:"finale",type:"tmx",src:"data/screen/victory.json"},{name:"alert_continua",type:"tmx",src:"data/screen/alert_resume.json"},{name:"alert_inserisci",type:"tmx",src:"data/screen/alert_insert.json"},{name:"yahoo",type:"audio",src:"data/sfx/"},{name:"ohno",type:"audio",src:"data/sfx/"},{name:"hurra",type:"audio",src:"data/sfx/"},{name:"right",type:"audio",src:"data/sfx/"},{name:"wrong",type:"audio",
src:"data/sfx/"},{name:"dice",type:"audio",src:"data/sfx/"},{name:"jump",type:"audio",src:"data/sfx/"},{name:"click",type:"audio",src:"data/sfx/"}]};
game.HomeScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("home");game.globals.message="";game.globals.score=[];game.globals.tabellone=[];game.globals.playernumGroup=[];game.globals.playernum=2;game.globals.playerhumanGroup=[];game.globals.playerhuman=1;game.globals.nomeGiocatore=[];game.globals.avatarGiocatore=[];game.globals.posizioneGiocatore=[];game.globals.statoGiocatore=[];game.globals.caselleUsate=["",[],[],[],[]];game.globals.currentPlayer=1;game.globals.roundNumber=
1;game.globals.valoreDado=0;game.globals.spostamenti=0;game.globals.cpuDice=!1;game.globals.movePlayer=0;game.globals.animLuna="idle"}});game.IntroScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("intro")}});game.InfoScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("info")}});
game.but_generic=me.GUI_Object.extend({init:function(b,c,a){a.image="transparent";this.x=a.x;this.y=a.y;a.spritewidth=a.width;a.spriteheight=a.height;this.parent(this.x,this.y,a)}});game.but_gioca=game.but_generic.extend({onClick:function(){me.state.change(me.state.MENU);audioEnabled&&me.audio.play("click");return!0}});game.but_gohome=game.but_generic.extend({onClick:function(){answerWindow||(me.state.change(me.state.MENU),audioEnabled&&me.audio.play("click"));return!0}});
game.but_help=game.but_generic.extend({onClick:function(){me.state.change(me.state.USER+2);audioEnabled&&me.audio.play("click");return!0}});game.but_info=game.but_generic.extend({onClick:function(){me.state.change(me.state.USER+1);audioEnabled&&me.audio.play("click");return!0}});game.but_link=game.but_generic.extend({onClick:function(){navigator.isCocoonJS?CocoonJS.App.openURL(MOREGAMESLINK):window.open(MOREGAMESLINK);audioEnabled&&me.audio.play("click");return!0}});
game.but_quit=game.but_generic.extend({onClick:function(){me.state.change(me.state.USER+7);audioEnabled&&me.audio.play("click");return!0}});
game.but_play=game.but_generic.extend({
	onClick:function(){
		if (typeof sdk !== 'undefined' && sdk.showBanner !== 'undefined') {sdk.showBanner();}
		game.globals.message="";game.globals.score=[];game.globals.tabellone=[];game.globals.playernumGroup=[];game.globals.playernum=2;game.globals.playerhumanGroup=[];game.globals.playerhuman=1;game.globals.nomeGiocatore=[];game.globals.avatarGiocatore=[];game.globals.posizioneGiocatore=[];game.globals.statoGiocatore=[];game.globals.caselleUsate=["",[],[],[],[]];game.globals.currentPlayer=1;game.globals.roundNumber=1;game.globals.valoreDado=0;game.globals.spostamenti=0;game.globals.cpuDice=!1;game.globals.movePlayer=0;0!=me.save.roundNumber?me.state.change(me.state.USER+6):me.state.change(me.state.USER+3);audioEnabled&&me.audio.play("click");return!0}
});
game.QuantiGiocatoriScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("quantiGiocatori");for(var b="C1-P R2-D C-3P S5-T C7-D MT-5 RX7 G-008 Asimo- Flender- Pegas0 Bender-345".split(" "),c=1;5>c;c++)game.globals.nomeGiocatore[c]=b[Math.ceil(Math.random()*b.length)-1]+c,game.globals.posizioneGiocatore[c]=0,game.globals.statoGiocatore[c]="";game.globals.avatarGiocatore=[]}});
game.but_playernum=me.GUI_Object.extend({init:function(b,c,a){this.val=a.value;game.globals.playernumGroup[this.val]=this;this.image_up=me.loader.getImage(this.val+"up");this.image_dw=me.loader.getImage(this.val+"dw");a.image=game.globals.playernum==this.val?this.val+"dw":this.val+"up";this.x=a.x;this.y=a.y;a.spritewidth=a.image.width;a.spriteheight=a.image.height;this.parent(this.x,this.y,a)},onClick:function(){for(var b=2;b<game.globals.playernumGroup.length;b++)game.globals.playernumGroup[b].image=
game.globals.playernumGroup[b].image_up;game.globals.playerhuman>this.val&&(game.globals.playerhuman=this.val);for(b=1;b<game.globals.playerhumanGroup.length;b++)game.globals.playerhumanGroup[b].image=b==game.globals.playerhuman?game.globals.playerhumanGroup[b].image_dw:game.globals.playerhumanGroup[b].image_up,b>this.val?(game.globals.playerhumanGroup[b].alpha=0,game.globals.playerhumanGroup[b].isClickable=!1):(game.globals.playerhumanGroup[b].alpha=1,game.globals.playerhumanGroup[b].isClickable=
!0);this.image=this.image_dw;game.globals.playernum=this.val;audioEnabled&&me.audio.play("click");return!0}});
game.but_playerhuman=me.GUI_Object.extend({init:function(b,c,a){this.val=a.value;game.globals.playerhumanGroup[this.val]=this;this.image_up=me.loader.getImage(this.val+"up");this.image_dw=me.loader.getImage(this.val+"dw");a.image=game.globals.playerhuman==this.val?this.val+"dw":this.val+"up";this.x=a.x;this.y=a.y;a.spritewidth=a.image.width;a.spriteheight=a.image.height;this.parent(this.x,this.y,a);this.val>game.globals.playernum&&(this.alpha=0,this.isClickable=!1)},onClick:function(){for(var b=1;b<
game.globals.playerhumanGroup.length;b++)game.globals.playerhumanGroup[b].image=game.globals.playerhumanGroup[b].image_up;this.image=this.image_dw;game.globals.playerhuman=this.val;audioEnabled&&me.audio.play("click");return!0}});
game.but_audioToggle=me.GUI_Object.extend({init:function(b,c,a){this.image_attivato=me.loader.getImage("attivato");this.image_disattivato=me.loader.getImage("disattivato");a.image=!0==game.globals.audio?this.image_attivato:this.image_disattivato;this.x=a.x;this.y=a.y;a.spritewidth=a.image.width;a.spriteheight=a.image.height;this.parent(this.x,this.y,a)},onClick:function(){this.image==this.image_attivato?(this.image=this.image_disattivato,game.globals.audio=!1):(this.image=this.image_attivato,game.globals.audio=
!0);audioEnabled&&me.audio.play("click");return!0}});
game.audioText=me.Renderable.extend({init:function(b,c,a){this.x=b;this.y=c;this.width=a.width;this.height=a.height;this.image_attivo=me.loader.getImage("attiva_txt");this.image_disattivo=me.loader.getImage("disattiva_txt");a.image=!0==game.globals.audio?this.image_disattivo:this.image_attivo;this.parent(new me.Vector2d(b,c),this.width,this.height)},draw:function(b){this.image=!0==game.globals.audio?this.image_disattivo:this.image_attivo;b.drawImage(this.image,this.x,this.y)}});
game.but_timerToggle=me.GUI_Object.extend({init:function(b,c,a){this.image_attivato=me.loader.getImage("attivato");this.image_disattivato=me.loader.getImage("disattivato");a.image=!0==game.globals.timer?this.image_attivato:this.image_disattivato;this.x=a.x;this.y=a.y;a.spritewidth=a.image.width;a.spriteheight=a.image.height;this.parent(this.x,this.y,a)},onClick:function(){this.image==this.image_attivato?(this.image=this.image_disattivato,game.globals.timer=!1):(this.image=this.image_attivato,game.globals.timer=
!0);audioEnabled&&me.audio.play("click");return!0}});
game.timerText=me.Renderable.extend({init:function(b,c,a){this.x=b;this.y=c;this.width=a.width;this.height=a.height;this.image_attivo=me.loader.getImage("attiva_txt");this.image_disattivo=me.loader.getImage("disattiva_txt");a.image=!0==game.globals.timer?this.image_disattivo:this.image_attivo;this.parent(new me.Vector2d(b,c),this.width,this.height)},draw:function(b){this.image=!0==game.globals.timer?this.image_disattivo:this.image_attivo;b.drawImage(this.image,this.x,this.y)}});
game.but_continue=game.but_generic.extend({onClick:function(){game.globals.avatarGiocatore.currentPlayer=1;me.state.change(me.state.USER+4);audioEnabled&&me.audio.play("click");return!0}});game.InputNomeScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("inputNome")}});
game.but_input=me.GUI_Object.extend({init:function(b,c,a){a.image="transparent";this.x=a.x;this.y=a.y;a.spritewidth=a.width;a.spriteheight=a.height;this.parent(this.x,this.y,a);this.font=new me.Font("arial, helvetica, sans-serif",50,"black","left");me.game.world.addChild(new game.TextInput,0);this.input=document.getElementsByTagName("INPUT")[0];this.input.focus();this.cursor=-10;this.cursorTiming=1},onClick:function(){this.input.focus();return!0},update:function(){return!0},draw:function(b){this.cursor+=
this.cursorTiming;10<this.cursor&&(this.cursorTiming=-1);-10>this.cursor&&(this.cursorTiming=1);0<this.cursorTiming?this.font.draw(b,this.input.value+"|",this.x,this.y):this.font.draw(b,this.input.value,this.x,this.y);return!0}});game.numero_giocatore=me.GUI_Object.extend({init:function(b,c,a){a.image="n"+game.globals.currentPlayer;this.x=a.x;this.y=a.y;a.spritewidth=a.image.width;a.spriteheight=a.image.height;this.parent(this.x,this.y,a)}});
game.but_avatar=me.GUI_Object.extend({init:function(b,c,a){this.val=a.value;a.image="big_"+this.val;this.x=a.x;this.y=a.y;a.spritewidth=a.image.width;a.spriteheight=a.image.height;this.parent(this.x,this.y,a);for(b=1;b<game.globals.avatarGiocatore.length;b++)this.val==game.globals.avatarGiocatore[b]&&(this.alpha=0,this.isClickable=!1)},onClick:function(){var b=document.getElementsByTagName("INPUT")[0].value;""!=b?(game.globals.avatarGiocatore[game.globals.currentPlayer]=this.val,game.globals.nomeGiocatore[game.globals.currentPlayer]=
b,game.globals.playerhuman>game.globals.currentPlayer?(game.globals.currentPlayer++,me.state.change(me.state.USER+4)):(game.globals.avatarGiocatore.currentPlayer=1,game.globals.avatarGiocatore.roundNumber=1,game.globals.winner=0,me.state.change(me.state.PLAY))):me.state.change(me.state.USER+8);audioEnabled&&me.audio.play("click");return!0}});
game.TextInput=me.Renderable.extend({init:function(){this.input=document.createElement("INPUT");this.input.setAttribute("type","text");this.input.setAttribute("maxlength","13");me.video.getWrapper().appendChild(this.input);this.input.focus()},destroy:function(){this.input.remove()}});game.finale=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("finale");answerWindow=!1}});
game.animLuna=me.ObjectEntity.extend({init:function(b,c,a){this.x=b;this.y=c;a.image="lunafinale";a.spritewidth=240;a.spriteheight=221;a.width=a.spritewidth;a.height=a.spriteheight;this.parent(this.x,this.y,a);this.renderable.addAnimation("finale",[0,1,2,3,4,5,4,5,4,5,4,5,6,7,8,7,6,5,6,7,8,7,6,5,6,7,8,7,6,5,4,5,4,5,4,5,4]);this.renderable.addAnimation("finaleLoop",[5,4]);this.renderable.setCurrentAnimation("finale","finaleLoop");this.renderable.setAnimationFrame(0)},update:function(b){this.parent(b);
return!0}});
game.nomeVincitore=me.Renderable.extend({init:function(b,c,a){this.x=b;this.y=c;this.width=a.width;this.height=a.height;this.parent(new me.Vector2d(b,c),this.width,this.height);this.font=new me.Font("Arial, Helvetica, sans-serif",60,"white","center");this.font.bold();this.font2=new me.Font("Arial, Helvetica, sans-serif",60,"black","center");this.font2.bold()},draw:function(b){this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2+1,this.y);this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],
this.x+this.width/2-1,this.y);this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2,this.y+1);this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2,this.y-1);this.font.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2,this.y)}});game.AlertPlayScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("alert_continua")}});
game.but_continua_si=game.but_generic.extend({onClick:function(){game.globals.audio=me.save.audio;game.globals.timer=me.save.timer;game.globals.roundNumber=me.save.roundNumber;game.globals.currentPlayer=me.save.currentPlayer;game.globals.playernum=me.save.playernum;game.globals.valoreDado=me.save.valoreDado;game.globals.playerhuman=me.save.playerhuman;game.globals.nomeGiocatore=me.save.nomeGiocatore;game.globals.avatarGiocatore=me.save.avatarGiocatore;game.globals.posizioneGiocatore=me.save.posizioneGiocatore;
game.globals.statoGiocatore=me.save.statoGiocatore;game.globals.movePlayer=me.save.movePlayer;audioEnabled&&me.audio.play("click");me.state.change(me.state.PLAY);return!0}});game.but_continua_no=game.but_generic.extend({onClick:function(){audioEnabled&&me.audio.play("click");me.state.change(me.state.USER+3);return!0}});game.AlertQuitScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("alert_esci")}});
game.but_esci_si=game.but_generic.extend({onClick:function(){gui.App.quit();return!0}});game.but_esci_no=game.but_generic.extend({onClick:function(){me.state.change(me.state.MENU);audioEnabled&&me.audio.play("click");return!0}});game.AlertInputScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("alert_inserisci")}});game.but_inserisci_ok=game.but_generic.extend({onClick:function(){me.state.change(me.state.USER+4);return!0}});var spk={};
game.PlayScreen=me.ScreenObject.extend({onResetEvent:function(){me.levelDirector.loadLevel("tabellone");me.sys.gravity=0;game.globals.caselleUsate[1]=[];game.globals.caselleUsate[2]=[];game.globals.caselleUsate[3]=[];game.globals.caselleUsate[4]=[];me.game.world.addChild(new game.avatarEntity(0,0,1),10);me.game.world.addChild(new game.avatarEntity(0,0,2),10);me.game.world.addChild(new game.avatarEntity(0,0,3),10);me.game.world.addChild(new game.avatarEntity(0,0,4),10);game.globals.quizPersonaNA=[];
game.globals.quizPersonaCG=[];game.globals.quizDuralex=[];game.globals.quizLiberi=[];answerWindow=confirmAnswer=!1;glowType="none"}});game.casellaEntity=me.ObjectEntity.extend({init:function(b,c,a){game.globals.tabellone[a.value]=[b,c,a.width,a.height,a.rule,a.text]}});
game.messageEntity=me.Renderable.extend({init:function(b,c){this.x=b;this.y=c;this.parent(new me.Vector2d(b,c),10,10);this.font1=new me.Font("arial, helvetica, sans-serif",22,"#000000","left");this.font2=new me.Font("arial, helvetica, sans-serif",15,"#000000","left");this.lastMessage="";this.log=[];this.colorlog=[];this.colors={};this.colors.cg1=P1_TXT_COLOR;this.colors.cg2=P2_TXT_COLOR;this.colors.cg3=P3_TXT_COLOR;this.colors.cg4=P4_TXT_COLOR;this.colorscpu=[[],["#333333"],["#333333"],["#444444"],
["#555555"]];this.glow=this.image=me.loader.getImage("glow");this.glowStart=this.image=me.loader.getImage("glowStart");this.glowGoal=this.image=me.loader.getImage("glowGoal")},draw:function(b){if("undefined"!=typeof game.globals.currentPlayer){switch(glowType){case "start":b.drawImage(this.glowStart,glowPos.x,glowPos.y-23);break;case "end":b.drawImage(this.glowGoal,glowPos.x-46,glowPos.y-15);break;default:b.drawImage(this.glow,glowPos.x,glowPos.y-14)}game.globals.message!=this.lastMessage&&(this.log.unshift(game.globals.message),
game.globals.currentPlayer>game.globals.playerhuman?this.colorlog.unshift(this.colorscpu[game.globals.currentPlayer]):this.colorlog.unshift(this.colors[game.globals.avatarGiocatore[game.globals.currentPlayer]]),this.lastMessage=game.globals.message);this.font1.fillStyle=this.colorlog[0];this.font1.draw(b,this.log[0],this.x,this.y);this.font2.fillStyle=this.colorlog[1];"undefined"!=typeof this.log[1]&&this.font2.draw(b,this.log[1],this.x,this.y+23);this.font2.fillStyle=this.colorlog[2];"undefined"!=
typeof this.log[2]&&this.font2.draw(b,this.log[2],this.x,this.y+39);this.font2.fillStyle=this.colorlog[3];"undefined"!=typeof this.log[3]&&this.font2.draw(b,this.log[3],this.x,this.y+55);this.font2.fillStyle=this.colorlog[4];"undefined"!=typeof this.log[4]&&this.font2.draw(b,this.log[4],this.x,this.y+71)}}});
game.dadoEntity=me.ObjectEntity.extend({init:function(b,c,a){a.image="dado";a.spritewidth=128;a.spriteheight=128;a.width=a.spritewidth;a.height=a.spriteheight;this.parent(b,c,a);this.renderable.addAnimation("idle",[0],120);this.renderable.addAnimation("1",[1],120);this.renderable.addAnimation("2",[2],120);this.renderable.addAnimation("3",[3],120);this.renderable.addAnimation("4",[4],120);this.renderable.addAnimation("5",[5],120);this.renderable.addAnimation("6",[6],120);this.renderable.addAnimation("running",
[1,4,6,5,2,4,3,1,4,5,1,4,3,1],80);this.renderable.setCurrentAnimation("idle");this.state="setpause"},update:function(b){switch(this.state){case "setpause":_this=this;setTimeout(function(){_this.state="idle"},100);this.state="pause";break;case "idle":this.renderable.setCurrentAnimation("idle");if(me.input.isKeyPressed("dice")||game.globals.cpuDice)game.globals.cpuDice=!1,this.state="running",audioEnabled&&me.audio.play("dice");break;case "running":this.renderable.isCurrentAnimation("running")||(this.renderable.setCurrentAnimation("running",
function(){this.state="result"}.bind(this)),this.renderable.setAnimationFrame(1));break;case "result":if(this.renderable.isCurrentAnimation("running")){var c=Number.prototype.random(1,6);c.round(0);this.renderable.setCurrentAnimation(c.toString());game.globals.valoreDado=c;game.globals.spostamenti=c}0==game.globals.valoreDado&&(this.state="setpause")}this.parent(b);return!0},destroy:function(){}});
game.controllerEntity=me.ObjectEntity.extend({init:function(b,c,a){this.parent(b,c,a);this.state="start";this.cpuHaTirato=!1;game.globals.comingFromQuiz=!1},update:function(b){switch(this.state){case "start":"freeze"==game.globals.statoGiocatore[game.globals.currentPlayer]?(game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+" miss a turn",game.globals.statoGiocatore[game.globals.currentPlayer]="unfreeze",_this=this,setTimeout(function(){_this.state=
"next";game.globals.statoGiocatore[game.globals.currentPlayer]=""},1E3),this.delay=200,this.state="wait"):(game.globals.valoreDado=0,this.state="dice");game.globals.comingFromQuiz=!1;break;case "dice":game.globals.message="Round "+game.globals.roundNumber+" : It's up to "+game.globals.nomeGiocatore[game.globals.currentPlayer];0!=game.globals.valoreDado&&(_this=this,setTimeout(function(){_this.state="result"},300),this.state="wait");game.globals.currentPlayer>game.globals.playerhuman&&!this.cpuHaTirato&&
0==game.globals.valoreDado&&(this.cpuHaTirato=game.globals.cpuDice=!0);break;case "result":game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+" scores "+game.globals.valoreDado;game.globals.movePlayer=game.globals.currentPlayer;game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+" moves by "+game.globals.valoreDado;this.state="movePlayer";break;case "movePlayer":0!=game.globals.movePlayer||
me.input.isKeyPressed("dice")||(this.state="check");break;case "check":var c=game.globals.posizioneGiocatore[game.globals.currentPlayer];if(null!=game.globals.tabellone[c][4]&&-1==indexOf.call(-1,c))switch(game.globals.caselleUsate[game.globals.currentPlayer].push(c),game.globals.tabellone[c][4]){case 2:if(!0===game.globals.comingFromQuiz){this.state="next";game.globals.comingFromQuiz=!1;break}game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+
", advances by two positions";audioEnabled&&me.audio.play("yahoo");game.globals.animLuna="esatto_3";_this=this;setTimeout(function(){game.globals.spostamenti=2;game.globals.movePlayer=game.globals.currentPlayer;_this.state="movePlayer"},1E3);this.state="wait";break;case 1:if(!0===game.globals.comingFromQuiz){this.state="next";game.globals.comingFromQuiz=!1;break}game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+", advances by one position";
audioEnabled&&me.audio.play("yahoo");game.globals.animLuna="esatto_2";_this=this;setTimeout(function(){game.globals.spostamenti=1;game.globals.movePlayer=game.globals.currentPlayer;_this.state="movePlayer"},1E3);this.state="wait";break;case -1:if(!0===game.globals.comingFromQuiz){this.state="next";game.globals.comingFromQuiz=!1;break}game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+", backs by two positions";audioEnabled&&me.audio.play("ohno");
game.globals.animLuna="sbagliato_1";_this=this;setTimeout(function(){game.globals.spostamenti=-1;game.globals.movePlayer=game.globals.currentPlayer;_this.state="movePlayer"},1E3);this.state="wait";break;case -2:if(!0===game.globals.comingFromQuiz){this.state="next";game.globals.comingFromQuiz=!1;break}game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+", backs by one position";audioEnabled&&me.audio.play("ohno");game.globals.animLuna=
"sbagliato_1";_this=this;setTimeout(function(){game.globals.spostamenti=-2;game.globals.movePlayer=game.globals.currentPlayer;_this.state="movePlayer"},1E3);this.state="wait";break;case "freeze":if(!0===game.globals.comingFromQuiz){this.state="next";game.globals.comingFromQuiz=!1;break}game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+", freeze one turn";audioEnabled&&me.audio.play("ohno");game.globals.animLuna="sbagliato_1";game.globals.statoGiocatore[game.globals.currentPlayer]=
"freeze";_this=this;setTimeout(function(){_this.state="next"},1500);this.state="wait";break;case "repeat":if(!0===game.globals.comingFromQuiz){this.state="next";game.globals.comingFromQuiz=!1;break}game.globals.message="Round "+game.globals.roundNumber+" : "+game.globals.nomeGiocatore[game.globals.currentPlayer]+", roll the dice again";audioEnabled&&me.audio.play("yahoo");game.globals.animLuna="esatto_2";_this=this;setTimeout(function(){_this.state="dice";game.globals.valoreDado=0;_this.cpuHaTirato=
!1},2E3);this.state="wait";break;case "quiz":if(!0===game.globals.comingFromQuiz){this.state="next";game.globals.comingFromQuiz=!1;break}else if(2==game.globals.comingFromQuiz){this.state="next";break}game.globals.message="Round "+game.globals.roundNumber+" : Quiz: "+game.globals.nomeGiocatore[game.globals.currentPlayer]+", answer the question";game.globals.comingFromQuiz=!0;_this=this;setTimeout(function(){_this.state="quiz_duralex"},1E3);this.state="wait";break;case "end":glowType="end";me.save.remove("roundNumber");
me.save.add({roundNumber:0});audioEnabled&&me.audio.play("hurra");this.state="victory";break;default:this.state="next"}else this.state="next",game.globals.comingFromQuiz=!1;break;case "next":this.cpuHaTirato=!1;game.globals.currentPlayer++;game.globals.currentPlayer>game.globals.playernum&&(game.globals.roundNumber++,game.globals.currentPlayer=1);me.save.remove("audio");me.save.remove("timer");me.save.remove("roundNumber");me.save.remove("currentPlayer");me.save.remove("playernum");me.save.remove("valoreDado");
me.save.remove("playerhuman");me.save.remove("nomeGiocatore");me.save.remove("avatarGiocatore");me.save.remove("posizioneGiocatore");me.save.remove("statoGiocatore");me.save.remove("movePlayer");me.save.remove("spostamenti");me.save.add({audio:game.globals.audio,timer:game.globals.timer,roundNumber:game.globals.roundNumber,currentPlayer:game.globals.currentPlayer,playernum:game.globals.playernum,valoreDado:game.globals.valoreDado,playerhuman:game.globals.playerhuman,nomeGiocatore:game.globals.nomeGiocatore,
avatarGiocatore:game.globals.avatarGiocatore,posizioneGiocatore:game.globals.posizioneGiocatore,statoGiocatore:game.globals.statoGiocatore,movePlayer:game.globals.movePlayer,spostamenti:game.globals.spostamenti});this.state="start";break;case "quiz_duralex":0==game.globals.quizDuralex.length&&(game.globals.quizDuralex=me.loader.getJSON("duralex"));var a=Math.round(Number.prototype.random(0,game.globals.quizDuralex.length-1)),c=game.globals.quizDuralex[a];game.globals.quizDuralex.splice(a,1);if(game.globals.currentPlayer>
game.globals.playerhuman)a=Math.round(Number.prototype.random(0,2)),game.globals.spostamenti=c.answers[a].score,game.globals.message=1==game.globals.spostamenti||-1==game.globals.spostamenti?"Round "+game.globals.roundNumber+" : "+game.globals.spostamenti+" position for "+game.globals.nomeGiocatore[game.globals.currentPlayer]:"Round "+game.globals.roundNumber+" : "+game.globals.spostamenti+" positions for "+game.globals.nomeGiocatore[game.globals.currentPlayer],_this=this,setTimeout(function(){game.globals.movePlayer=
game.globals.currentPlayer;_this.state="movePlayer"},1E3),this.state="wait";else{game.globals.spostamenti="quiz";var a=me.video.getWidth(),d=me.video.getHeight(),f=c.question,e=[0,1,2],e=shuffle(e),g=c.answers[e[0]].answer,h=c.answers[e[0]].score,k=c.answers[e[1]].answer,l=c.answers[e[1]].score,m=c.answers[e[2]].answer,c=c.answers[e[2]].score;this.question=new game.Quiz(a/2,d/2,"bg_quiz_duralex",f);me.game.world.addChild(this.question,999);this.answers1=new game.answers(a/2,0.4*d,g,h,"1",!0);me.game.world.addChild(this.answers1,
1E3);this.answers2=new game.answers(a/2,0.55*d,k,l,"2",!0);me.game.world.addChild(this.answers2,1E3);this.answers3=new game.answers(a/2,0.7*d,m,c,"3",!0);me.game.world.addChild(this.answers3,1E3);this.timer=0;this.state="risposta_duralex"}break;case "risposta_duralex":confirmAnswer||(0==this.timer&&(this.timer=me.timer.getTime()+1E3*game.globals.answerTime),game.globals.answerTimer=Math.floor((this.timer-me.timer.getTime())/1E3));!0==game.globals.timer&&me.timer.getTime()>this.timer&&(audioEnabled&&
me.audio.play("wrong"),this.timer=me.timer.getTime()+1E17,puntiRisposta=-2,game.globals.spostamenti=puntiRisposta,confirmAnswer=!0);"quiz"!=game.globals.spostamenti&&(me.game.world.removeChild(this.question),me.game.world.removeChild(this.answers1),me.game.world.removeChild(this.answers2),me.game.world.removeChild(this.answers3),_this=this,setTimeout(function(){game.globals.movePlayer=game.globals.currentPlayer;_this.state="movePlayer"},1E3),confirmAnswer=!1,this.state="wait",game.globals.message=
1==game.globals.spostamenti||-1==game.globals.spostamenti?"Round "+game.globals.roundNumber+" : "+game.globals.spostamenti+" position for "+game.globals.nomeGiocatore[game.globals.currentPlayer]:"Round "+game.globals.roundNumber+" : "+game.globals.spostamenti+" positions for "+game.globals.nomeGiocatore[game.globals.currentPlayer],audioEnabled&&(0<game.globals.spostamenti?me.audio.play("right"):me.audio.play("wrong")));break;case "victory":game.globals.message=game.globals.nomeGiocatore[game.globals.currentPlayer]+
" WINS!!! ",glowType="end",this.state="wait",setTimeout(function(){me.state.change(me.state.USER+5)},4E3)}this.parent(b);return!0},destroy:function(){}});
game.Quiz=me.Renderable.extend({init:function(b,c,a,d){settings={};this.image=this.image=me.loader.getImage(a);this.bgname=a;this.spritewidth=this.image.width;this.spriteheight=this.image.height;this.x=b-this.spritewidth/2;this.y=c-this.spriteheight/2;this.textX=b;this.parent(new me.Vector2d(0,0),1,1);this.font=new me.Font("arial, helvetica, sans-serif",20*(1-((300>d.length?d.length:300)-30)/270)+20,"black","left");this.font.textAlign="center";this.font2=new me.Font("arial, helvetica, sans-serif",
32,"#0000ff","left");this.font2.textAlign="center";this.text=d;answerWindow=!0},draw:function(b){b.drawImage(this.image,this.x,this.y);if(!confirmAnswer){var c=this.text,a=this.font.measureText(b,c).width,a=Math.ceil(a/770);chWidth=c.length/a;for(var d=0,f=1;f<a;f++){for(var e=0;" "!=c.charAt(d+chWidth-e);)e++;d=d+chWidth-e;c=c.replaceAt(d,"\n");if(f==a-1&&(e=c.substr(d+1,c.length),770<this.font.measureText(b,e).width)){for(e=0;" "!=c.charAt(d+chWidth-e);)e++;d=d+chWidth-e;c=c.replaceAt(d,"\n")}}this.font.draw(b,
c,this.textX,this.y+100);game.globals.timer&&-1<game.globals.answerTimer&&game.globals.answerTimer<game.globals.answerTime&&("bg_quiz_liberi"==this.bgname?this.font2.draw(b,"Remaining Time: "+game.globals.answerTimer+"",512,530):this.font2.draw(b,"Remaining Time: "+game.globals.answerTimer+"",512,650))}},destroy:function(){answerWindow=!1}});
game.answers=me.GUI_Object.extend({init:function(b,c,a,d,f,e){this.duralex=!1;"undefined"!=typeof e&&(this.duralex=e);this.key=f;this.text=a;this.score=d;settings={};settings.image=this.image=me.loader.getImage("quiz_button");settings.spritewidth=settings.image.width;settings.spriteheight=settings.image.height;this.x=b-settings.spritewidth/2;this.y=c-settings.spriteheight/2;this.width=settings.spritewidth;settings.width=settings.spritewidth;settings.height=settings.spriteheight;this.parent(b-settings.spritewidth/
2,c-settings.spriteheight/2,settings);this.charsize=b=15*(1-((250>a.length?a.length:250)-20)/230)+15;this.font=new me.Font("arial, helvetica, sans-serif",b,"red","center");me.game.world.moveToTop(this.renderable)},draw:function(b){if(!confirmAnswer){var c=this.key+") "+this.text;b.drawImage(this.image,this.x,this.y);var a=this.font.measureText(b,c).width,a=Math.ceil(a/750);chWidth=c.length/a;for(var d=0,f=1;f<a;f++){for(var e=0;" "!=c.charAt(d+chWidth-e);)e++;d=d+chWidth-e;c=c.replaceAt(d,"\n");if(f==
a-1&&(e=c.substr(d+1,c.length),770<this.font.measureText(b,e).width)){for(e=0;" "!=c.charAt(d+chWidth-e);)e++;d=d+chWidth-e;c=c.replaceAt(d,"\n")}}this.font.draw(b,c,this.x+this.width/2,this.y+40-0.7*(a-1)*this.charsize)}},update:function(b){!confirmAnswer&&me.input.isKeyPressed(this.key)&&(audioEnabled&&me.audio.play("click"),puntiRisposta=this.score,duralex=this.duralex,confirmAnswer=!0,divDidattica.style.display="block");this.parent(b);return!0},onClick:function(){confirmAnswer||(puntiRisposta=
this.score,duralex=this.duralex,confirmAnswer=!0,game.globals.spostamenti=puntiRisposta,audioEnabled&&me.audio.play("click"));return!0}});
game.but_conferma=me.GUI_Object.extend({init:function(b,c){settings={};settings.image=this.image=me.loader.getImage("conferma_button");settings.spritewidth=settings.image.width;settings.spriteheight=settings.image.height;this.x=b-settings.spritewidth/2;this.y=c-settings.spriteheight/2;this.width=settings.spritewidth;settings.width=settings.spritewidth;settings.height=settings.spriteheight;this.parent(b-settings.spritewidth/2,c-settings.spriteheight/2,settings);this.font=new me.Font("arial, helvetica, sans-serif",
25,"black","center");me.game.world.moveToTop(this.renderable)},draw:function(b){confirmAnswer&&(b.drawImage(this.image,this.x,this.y),this.font.fillStyle="black",this.font.draw(b,"Prosegui",this.x+this.width/2,this.y+15))},update:function(b){confirmAnswer&&me.input.isKeyPressed("continue")&&(game.globals.spostamenti=puntiRisposta,audioEnabled&&me.audio.play("click"),confirmAnswer=!1);this.parent(b);return!0},onClick:function(){confirmAnswer&&(game.globals.spostamenti=puntiRisposta,audioEnabled&&me.audio.play("click"));
return!0}});game.didattica=me.Renderable.extend({init:function(b,c,a){this.parent(new me.Vector2d(0,0),1,1);divDidattica=document.createElement("div");divDidattica.id="didattica";divDidattica.style.height=c+"%";divDidattica.innerHTML=a;me.video.getWrapper().appendChild(divDidattica)},update:function(){var b=me.video.getScreenCanvas().width,c=me.video.getPos().left+0.12*b;divDidattica.style.left=c.toString()+"px";divDidattica.style.width=(b-0.27*b).toString()+"px"},destroy:function(){divDidattica.remove()}});
function gestisciEspessioniLuna(b,c){0<b?(audioEnabled&&2>=b&&me.audio.play("right"),audioEnabled&&2<b&&me.audio.play("rightgrande"),game.globals.animLuna="esatto_"+Number.prototype.random(1,4).toString()):0>b?(audioEnabled&&me.audio.play("wrong"),game.globals.animLuna="sbagliato_"+Number.prototype.random(1,8).toString()):(game.globals.comingFromQuiz=2,c?(audioEnabled&&me.audio.play("rightgrande"),game.globals.animLuna="esatto_"+Number.prototype.random(1,4).toString()):(audioEnabled&&me.audio.play("meh"),
game.globals.animLuna="meh_"+Number.prototype.random(1,8).toString()))}
game.avatarEntity=me.ObjectEntity.extend({init:function(b,c,a){settings={};settings.id=a;settings.id<=game.globals.playernum&&(this.x=game.globals.tabellone[0][0]+game.globals.tabellone[0][2]/2-35+Number.prototype.random(-20,20),this.y=game.globals.tabellone[0][1]+game.globals.tabellone[0][3]/2-65,settings.image=settings.id>game.globals.playerhuman?"robot":game.globals.avatarGiocatore[settings.id],settings.spritewidth=70,settings.spriteheight=70,settings.width=settings.spritewidth,settings.height=
settings.spriteheight,this.parent(this.x,this.y,settings),this.addShape(new me.Rect(new me.Vector2d(0,0),70,70)),this.id=settings.id,this.state="idle",this.steps=0,-1!=game.globals.posizioneGiocatore[settings.id]&&(b=game.globals.posizioneGiocatore[settings.id],this.pos.x=game.globals.tabellone[b][0]+game.globals.tabellone[b][2]/2-35+Number.prototype.random(-20,20),this.pos.y=game.globals.tabellone[b][1]+game.globals.tabellone[b][3]/2-65))},update:function(b){switch(this.state){case "idle":if(game.globals.currentPlayer==
this.id){answerWindow?me.game.world.moveToBottom(this):me.game.world.moveToTop(this);var c=game.globals.posizioneGiocatore[game.globals.currentPlayer];glowPos.x=game.globals.tabellone[c][0];glowPos.y=game.globals.tabellone[c][1]}game.globals.movePlayer==this.id&&(this.state="setmove",this.steps=game.globals.spostamenti);break;case "setmove":me.game.world.moveToTop(this);if(0<this.steps)c=game.globals.posizioneGiocatore[game.globals.currentPlayer],"end"==game.globals.tabellone[c][4]?(this.target=game.globals.posizioneGiocatore[this.id]-
1,this.steps*=-1,this.steps++,!0==game.globals.comingFromQuiz):(this.target=game.globals.posizioneGiocatore[this.id]+1,this.steps--);else if(0>this.steps)this.target=game.globals.posizioneGiocatore[this.id]-1,this.steps++;else{this.state="idle";me.game.world.moveToBottom(this.renderable);game.globals.movePlayer=0;break}this.coordinateTarget=new me.Vector2d;this.coordinateTarget.x=game.globals.tabellone[this.target][0]+game.globals.tabellone[this.target][2]/2-35+Number.prototype.random(-20,20);this.coordinateTarget.y=
game.globals.tabellone[this.target][1]+game.globals.tabellone[this.target][3]/2-65;this.state="move";audioEnabled&&me.audio.play("jump");glowPos.x=game.globals.tabellone[this.target][0];glowPos.y=game.globals.tabellone[this.target][1];break;case "move":this.pos.x-=(this.pos.x-this.coordinateTarget.x)/5,this.pos.y-=(this.pos.y-this.coordinateTarget.y)/5,this.pos.x<this.coordinateTarget.x?this.flipX(!1):this.flipX(!0),1>Math.abs(this.pos.x-this.coordinateTarget.x)&&1>Math.abs(this.pos.y-this.coordinateTarget.y)&&
(this.state="setmove",game.globals.posizioneGiocatore[this.id]=this.target),glowPos.x=game.globals.tabellone[this.target][0],glowPos.y=game.globals.tabellone[this.target][1]}this.parent(b);return!0}});
game.showCurrentPlayerEntity=me.Renderable.extend({init:function(b,c,a){this.x=b;this.y=c;this.width=a.width;this.height=a.height;this.parent(new me.Vector2d(b,c),this.width,this.height);this.font=new me.Font("arial, helvetica, sans-serif",20,"white","center");this.font2=new me.Font("arial, helvetica, sans-serif",20,"black","center")},draw:function(b){this.image=void 0!=game.globals.avatarGiocatore[game.globals.currentPlayer]?me.loader.getImage("big_"+game.globals.avatarGiocatore[game.globals.currentPlayer]):
me.loader.getImage("big_robot");this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2+1,this.y);this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2-1,this.y);this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2,this.y+1);this.font2.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],this.x+this.width/2,this.y-1);this.font.draw(b,game.globals.nomeGiocatore[game.globals.currentPlayer],
this.x+this.width/2,this.y);b.drawImage(this.image,this.x+this.width/2-this.image.width/2,this.y+20)}});
game.EspressioniLunaEntity=me.ObjectEntity.extend({init:function(b,c,a){this.x=b;this.y=c;a.image="luna";a.spritewidth=151;a.spriteheight=174;a.width=a.spritewidth;a.height=a.spriteheight;this.parent(this.x,this.y,a);this.addShape(new me.Rect(new me.Vector2d(0,0),a.spritewidth,a.spriteheight));this.renderable.addAnimation("idle",[0,0,0,0,0,0,0,0,0,0,56,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,56,0,0,0,56,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,56,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0]);this.renderable.addAnimation("esatto_1",[0,1,2,3,4,5,4,5,4,5,4,5,6,7,8,7,6,5,6,7,8,7,6,5,6,7,8,7,6,5,4,5,4,5,4,5,4,3,2,1,0]);this.renderable.addAnimation("esatto_2",[0,10,11,12,13,14,13,14,13,14,13,14,13,14,13,14,13,12,11,10,0]);this.renderable.addAnimation("esatto_3",[0,16,17,18,19,20,19,20,19,20,19,20,19,20,19,20,18,18,17,16,0]);this.renderable.addAnimation("esatto_4",[0,22,23,24,25,26,25,26,25,26,25,26,25,26,25,26,24,23,22,0]);this.renderable.addAnimation("sbagliato_1",
[0,28,29,30,31,32,33,34,35,36,35,36,35,36,35,36,35,34,33,32,31,30,29,28,0]);this.renderable.addAnimation("sbagliato_2",[0,38,39,40,41,42,41,42,41,42,41,42,41,40,39,38,0]);this.renderable.addAnimation("sbagliato_3",[0,44,45,46,47,48,47,48,47,48,47,48,47,46,45,44,0]);this.renderable.addAnimation("sbagliato_4",[0,50,51,52,53,54,53,54,53,54,57,58,59,60,61,60,61,60,61,60,59,58,57,52,51,50,0]);this.renderable.addAnimation("sbagliato_5",[0,63,64,65,66,67,66,67,66,67,66,67,66,65,64,63,0]);this.renderable.addAnimation("sbagliato_6",
[0,69,70,71,72,74,75,76,77,78,79,80,81,82,75,76,77,78,79,80,81,82,72,71,70,69,0]);this.renderable.addAnimation("sbagliato_7",[0,84,85,86,87,87,87,87,87,87,87,87,86,85,84,0]);this.renderable.addAnimation("sbagliato_8",[0,99,100,101,102,102,102,102,102,102,102,101,100,99,0]);this.renderable.addAnimation("meh_1",[0,89,90,91,92,92,92,92,92,92,92,91,90,89,0]);this.renderable.addAnimation("meh_2",[0,94,95,96,97,97,97,97,97,97,97,96,95,94,0]);this.renderable.addAnimation("meh_3",[0,104,105,106,107,107,107,
107,107,107,106,105,104,0]);this.renderable.addAnimation("meh_4",[0,109,110,111,112,112,112,112,112,112,111,110,109,0]);this.renderable.addAnimation("meh_5",[0,114,115,116,117,118,118,118,118,118,117,116,115,114,0]);this.renderable.addAnimation("meh_6",[0,120,121,122,123,123,123,123,123,123,123,122,121,120,0]);this.renderable.addAnimation("meh_7",[0,125,126,127,128,129,129,129,129,129,129,128,127,126,125,0]);this.renderable.addAnimation("meh_8",[0,131,132,133,134,134,134,134,134,134,134,134,134,132,
131,0]);this.renderable.addAnimation("victory",[0,136,137,138,139,140,139,140,139,140,139,140,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,159,159,159,159,159,159,159,159,159,159,159,159]);this.renderable.setCurrentAnimation("victory")},update:function(b){this.renderable.isCurrentAnimation(game.globals.animLuna)||this.renderable.setCurrentAnimation(game.globals.animLuna,function(){game.globals.animLuna="idle"}.bind(this));this.parent(b);return!0}});
var indexOf=function(b){indexOf="function"===typeof Array.prototype.indexOf?Array.prototype.indexOf:function(b){for(var a=-1,d=-1,a=0;a<this.length;a++)if(this[a]===b){d=a;break}return d};return indexOf.call(this,b)};String.prototype.replaceAt=function(b,c){return this.substr(0,b)+c+this.substr(b+c.length)};function shuffle(b){var c,a,d=b.length;if(d)for(;--d;)a=Math.floor(Math.random()*(d+1)),c=b[a],b[a]=b[d],b[d]=c;return b};
